### PR TITLE
update to ffmpeg codecpar

### PR DESCRIPTION
**Pull request by uknunknown**
- update to ffmpeg codecpar

### CODE REVIEW

**Comment by uknunknown** [comment]
@Flole998 is your call ... I will remove the define on later submit if we don't have any problems.

**Comment by Flole998** [comment]
Remove the define, we can always revert a commit if things go wrong. It's literally 2 clicks for me and a PR is reverted.

**Comment by uknunknown** [comment]
Done.

**Comment by uknunknown** [comment]
I don;t understand why it failed ... can you run the check manually?

**Comment by Flole998** [comment]
It says internal error, so not your fault. Yes I can run it again, or if you squash your commits it will also re-run ;) If it fails again just give it some time and I'll re-run it tomorrow.

**Comment by uknunknown** [comment]
I don't understand why githubshows two submits ... I have only one in github desktop.
sqashed

**Comment by Flole998** [comment]
Try a force-push

**Comment by uknunknown** [comment]
it up to date:
force

**Comment by CvH** [comment]
> I don't understand why githubshows two submits

both commits from you PR does not belong to any branch at your repo :)

Likewise because you master branch (btw you should use topic branches to pr and never push commits to master) is out of sync with the tvh master branch for some reason and github doesn't detect it.
I would try to add a dummy commit to your master and check if the pr gets updated, if it does just drop the commit again and push again.

**Comment by uknunknown** [comment]
> btw you should use topic branches to pr and never push commits to master

Let me highlight what I am doing ... in order for you to be able to tell me what I am doing wrong:
1. (development) I always start any changes by cloning master into my Ubuntu 
2. using VSC I am performing all changes + debugging
3. VSC will show me what files I changed (also ./Autobuild.sh will highlight in RED those files)
4. when I am ready I clone again on my Windows (with githubdesktop)
5. override the files that I changed on with VSC (using winscp) on my local windows github folder
6. Githubdestop will show me the changes ... for a second review. maybe repeat 3-6 if I forgot to remove something that is not required.
7. press Commit --> now because I don't have Write access it will ask me to Fork
8. it is going to ask me is for My person use or for Contribution to project --> I select Contribution to project.
9. now I have to go to github site and initiate PR

If I have to change something after PR was created.
1. I do perform the tests and copy with winscp from Ubuntu to my local Github project 
2. using GithubDesktop push the changes to my master.
3. switch to my githubdesktop history tab and select the tabs that I want to squash --> right click Squash
4. after that will ask me if I am sure --> Yes. and will propose me to Force push.
5. I press the Force push and magically that will be pushed also into my PR (until now).

What I need to change in my flow?
thank you.

**Comment by CvH** [comment]
I have to admit I have no idea how GHdesktop works in particular, what in general works well
1. fork the tvh repo at GH
2. clone forked master to your local (or update if you have already)
3. create a local topic branch from a fresh local master for ex `git checkout -b update_to_codecpar`
4. do all you changes needed and commit them
5. push your changes to you forked repo at GH (there you are allowed to squash and whatnot) thats create also the topic branch at you GH repo
6. create a PR at Tvh from your topic branch
7. later delete your topic branch

I can not really follow what you try to copy with WinSCP all the time so maybe I missing here a problem at some stage :)
You could just use WSL so you have the best from both worlds without major problems.
For example you could start a Ubuntu or a distro you like at WSL. 
Put/Clone your project at `c:\yourproject\whatever` at your native Windows folder and edit with VSC. Go to your WSL and change to `/mnt/c/yourproject/whatever` and compile tvh.

In general if your changes are at your GH repo everything is okay and should get picked up. For your case I would suggest 
```
I would try to add a dummy commit to your master and check if the pr gets updated, if it does just drop the commit again and push again.
```

**Comment by uknunknown** [comment]
> For your case I would suggest

your recommendation worked. I will try to understand your flow.

**Comment by Flole998** [comment]
> Can you tell me if with your method I can make 2-3 (or mode branches), form the same master version, and open 2-3 or more PRs (assuming are affecting different regions of source code) in parallel? This will help with my development ...

Yes, you can even switch between them, that's the entire concept of branches.

**Pull request merged**
