### PR TITLE
corect M3U playlist Logo tag

### PR DESCRIPTION
**Pull request by djlucas123456**
corect M3U playlist Logo tag

### CODE REVIEW

**Comment by Saentist** [comment]
Isn't there must be do same for importing playlist?

**Comment by djlucas123456** [comment]
> 
> 
> Isn't there must be do same for importing playlist?

I think it doesn't matter if it's for an imported playlist. this is a correct tag

**Comment by Flole998** [comment]
@Saentist The import playlist code already recognizes both tags

**Review by Flole998 — COMMENTED** [review]
Is there any reason why you didn't change it in line 517 aswell?

**Review by Flole998 — COMMENTED** [review]
Is there any reason why you didn't change it in line 517 aswell?

**Comment by djlucas123456** [comment]
> 
> 
> Is there any reason why you didn't change it in line 517 aswell?

oops .. I didn't notice. added. :-)

**Comment by Flole998** [comment]
Can you squash your commits together please?

**Comment by Flole998** [comment]
Closing due to inactivity

**Comment by jasimancas** [comment]
It's possible fix this please?

**Comment by Flole998** [comment]
It is not squashed and it is missing a meaningful commit message.

**Comment by chewitt** [comment]
The "patch-1" branch name suggests it was done with the GitHub editor. That normally correlates to a low chance of the contributor understanding the requirement and/or being able to self-fix the problem.

**Pull request closed without merging**
