### PR TITLE
Fixed cross-compilation errors (master)

### PR DESCRIPTION
**Pull request by nurtext**
Especially when compiling for Synology DSM.

### CODE REVIEW

**Comment by perexg** [comment]
Uff. It looks like that the used TAILQ macros are wrong. The problem is that there may be more errors than compilation ones. Could you upload somewhere the used <sys/queue.h> file ?

**Comment by nurtext** [comment]
@perexg I didn't used any file special file and the macros already did exist, except the TAILQ_EMPTY one which I added from the linux docs.

**Comment by perexg** [comment]
Sorry, appearently &lt;&gt; must be typed in html. Could you upload somewhere the used <sys/queue.h> file ?

**Comment by nurtext** [comment]
@perexg I still don't get it. Sorry. I just added the missing TAILQ_EMPTY macro. No special file, just the macro with #ifndef statement just in case sys/queue.h is missing it - as you can see in http://man7.org/linux/man-pages/man3/queue.3.html

**Comment by perexg** [comment]
The problem is that macros should define the contents in {} blocks to not void the if something then something without brackets. Usually 'do {} while (0)' construct is used.

**Comment by nurtext** [comment]
@perexg Okay, but almost every source for sys/queue.h which can be found is using the macros without brackets. See:

http://www.opensource.apple.com/source/xnu/xnu-1456.1.26/bsd/sys/queue.h
http://unix.superglobalmegacorp.com/xnu/newsrc/bsd/sys/queue.h.html
etc.

**Comment by perexg** [comment]
The 'do {} while(0)' is OK. If you have this for TAILQ_INSERT_HEAD() than the compiler should not complain. What's the compilation error in your case?

**Comment by nurtext** [comment]
@perexg Seems we got things terribly wrong in this discussion. I will clearify: TAILQ_EMPTY is missing in sys/queue.h when cross compiling for Synology DSM. Compiler was complaining about this. Someone else decided to hardcode the macro in form of a sourcecode patch during cross compilation. I thought it would be better to add the missing TAILQ_EMPTY macro using the #ifndef directive. In addition to that, the compiler complains about missing curly brackets, which I added and included into this PR as well. After doing this all cross compilation errors are gone and tvheadend runs fine.

**Comment by perexg** [comment]
My all questions were for "In addition to that, the compiler complains about missing curly brackets, which I added and included into this PR as well. ". There's no reason that compiler complains when macros are using the 'do { code } while(0)' construct. It should already cover the {} need. The TAILQ_EMPTY extension is fine.

**Comment by nurtext** [comment]
@perexg Sadly the compiler does complain about this :cry: 
```
src/service.c: In function 'service_destroy':
src/service.c:860: error: expected expression before 'else'
src/service.c: In function 'service_create0':
src/service.c:916: error: expected expression before 'else'
```

**Comment by perexg** [comment]
@nurtext : Then, could you show me the used &lt;sys/queue.h&gt; file ?

**Comment by nurtext** [comment]
Sure:
https://gist.github.com/nurtext/1cec1dcf90bd0ebda78a

From Synology's official cross-compiling source:
http://sourceforge.net/projects/dsgpl/files/DSM%204.3%20Tool%20Chains/Intel%20x86%20Linux%203.2.40%20%28Bromolow%29

**Comment by nurtext** [comment]
@perexg And sorry for misunderstanding you in the first place :wink: Hope you're not mad with me now…

**Comment by perexg** [comment]
Thanks. I added own copy of sys/queue.h version 8.5 to the tvheadend sources and removed all duplicate definitions from src/queue.h .

The problem is that old version 8.3 uses define {} instead define do {} while(0) which causes problems like:

<pre>
  if (cond)
    { macro_code };
  else
   something;
</pre>

instead:

<pre>
  if (cond)
   do { macro_code } while(0);
 else
  something;
</pre>

The ';' in first example means end-of-condition, so 'else' is correctly reported at wrong place.

**Comment by nurtext** [comment]
@perexg Could please make a backport for release 4.0?

**Pull request closed without merging**
