### PR TITLE
autobuild: add build target for raspbian-buster

### PR DESCRIPTION
**Pull request by mpmc**
Please also cherry pick 2d020e8f214c6817f6b36271d82039c95a7d1447 for release/4.2, note these builds will fail until @andoma has a chance to add the required buildenv to doozer.io

### CODE REVIEW

**Comment by oldium** [comment]
Any update on this topic, please? Thanks.

**Comment by mpmc** [comment]
> 
> 
> Any update on this topic, please? Thanks.

Still waiting for it to be merged (pokes @perexg) and for the build-env to be added to doozer.io (also pokes @andoma )

**Comment by lloyda** [comment]
Just wondering if there was any update on a getting a Raspbian Buster build for 4.3?

**Comment by Flole998** [comment]
@andoma I'm currently trying to fix all the doozer build issues, unfortunately we are still missing the raspbian-buster build-env. Could you please add that so we can get a green checkmark on doozer aswell?

**Comment by oldium** [comment]
Any update @andoma, please? Still awaiting Raspbian Buster support...

**Comment by Flole998** [comment]
Reverting this commit for now as it has no use at the moment....

**Pull request merged**
