### PR TITLE
When deleteing a dvr entry, try to also delete any KODI EDL files.

### PR DESCRIPTION
**Pull request by carpa5**
Hi. I am new at this so please be patient. 
I have a job that runs after a recording has finished. It uses "Comskip" to create a KODI compatible EDL file. When I was deleting a recording the video file got removed, but the EDL file did not. This commit fixes that situation by deleting the associated EDL file. 

Richard

### CODE REVIEW

**Comment by perexg** [comment]
I don't like this. It would be better to run a custom script when the entry was removed - like 'post-processor command'.

**Comment by perexg** [comment]
But thanks for your contribution!

**Comment by carpa5** [comment]
OK, if this is the wrong way, can you point me to more info on  'post-processor command' after submitting a delete on a dvr entry. I have just recently switched from mythtv as the backend and so this is all very new to me. 

Thanks

**Comment by perexg** [comment]
I implemented post-remove command in 0fda5efee3e768259a6cbe9d4177209778c12714 . The usage is similar to post-processor command. See help for the post-processor command details.

**Comment by carpa5** [comment]
Thanks for the quick fix. It is great that you are so receptive to requests. I am implementing the post-remove script now.

**Pull request closed without merging**
