### PR TITLE
#4182: Add 'duplicate handling' - feature in DVR-Profiles

### PR DESCRIPTION
**Pull request by lomion0815**
This patch adds drop-down list to "DVR profile "configuration which is then used by default for newly created "autorec" entry. Can be altered in "Autorec" configuration.
Solves issue #4182
Moved PR 1316 to this PR.

### CODE REVIEW

**Comment by Flole998** [comment]
Could you please squash your commits together?

**Comment by lomion0815** [comment]
"Sqash" done and rebased to latest master

**Comment by Flole998** [comment]
@dave-p This is kinda related (or possibly the same) of what you did in #1488, maybe we can improve your code based on this?

**Comment by dave-p** [comment]
They are similar but not quite the same. 
#1488 adds a Duplicate Handling drop-down to the autorec config screen which is used for all newly-created autorecs. However changing the config entry has no effect on existing autorecs. #1330 does the same but also adds an entry "Use config setting" to the individual autorec edit screen; if this setting is selected (the default) then changing the config entry will change all existing as well as future autorecs.
#1488 (obviously) meets my needs. I'm not sure what the "expected behaviour" should be, changing existing autorecs does seem a little dangerous.

**Comment by lomion0815** [comment]
Hi, to my understanding this is the usual way TVHeadend configuration escalates changes: Changes in the recording settings are used for all (auto)recordings unless set differently in the specific autorec. Take the early start and late stop settings for instance.

**Comment by Flole998** [comment]
Replaced by #1661

**Pull request closed without merging**
