### PR TITLE
Fix IPTV glitches

### PR DESCRIPTION
**Pull request by mcaptur**
Some channels used to glitch quite badly on TVH but play/recover fine on vlc(directly).. this patch makes TVH behave like vlc

### CODE REVIEW

**Comment by Trujulu** [comment]
Do you mean with glitches VLC cant recover properly from missing packets?

**Comment by mcaptur** [comment]
sorry message was not clear
VLC opening stream directly short glitch but full recovers quickly
When using tvheadend gliches are much more severe and sometime does not even recover (when using htsp - did not test extensively with passthrough)

**Comment by perexg** [comment]
How did you this analysis? The PCR clocks should be regulary updated, so the diff should not be big.

The only thing to consider is to increase the kernel socket UDP buffer settings (udp_bind() calls (setsockopt)). It may be worth to set internal kernel buffers to 512kB or so.

**Comment by mcaptur** [comment]
piping via ffmpeg is actually better

**Comment by EItanMao** [comment]
How do I apply these patches?

**Pull request closed without merging**
