### PR TITLE
Add some more Tooltips!

### PR DESCRIPTION
**Pull request by mpmc**
@ProfYaffle Could you take a look please? :cool:

### CODE REVIEW

**Comment by ProfYaffle** [comment]
Happy to look later, but immediate thought is that some of these seem very long - how do they appear on screen, have you tested at all? I'm just wondering if I'm reviewing for content or brevity...

**Comment by mpmc** [comment]
@ProfYaffle Yes I have tested them & they look fine to me on screen they only appear when you mouse over an element. like this..
Example

Yes some can be long and some have been stolen from the help but it's not like they prevent you from using the element, I also suggested to @perexg to add an option to hide them for those that find them annoying but I think in the long run it'll help with people constantly asking "What does xyz do?".

*I'm just wondering if I'm reviewing for content or brevity* both really it's always good to have another set of eyes IMO.

I was also thinking that we could use these somehow to generate the help docs and where necessary (in the docs) add more information.

**Comment by perexg** [comment]
Merged. Thanks. I also added the possibility to disable quick tips in the general config.

**Comment by perexg** [comment]
BTW: Generation of the docs templates from the idnode data is not a bad idea.

**Pull request closed without merging**
