### PR TITLE
update to ffmpeg 6.0

### PR DESCRIPTION
**Pull request by uknunknown**
update to ffmpeg 6.0

### CODE REVIEW

**Comment by uknunknown** [comment]
The only gotcha with this PR is the discontinuity of thread_safe_callbacks
In the API change document for 6.0:

> 2020-11-27 - a83098ab03 - lavc 58.114.100 - avcodec.h
>  Deprecate AVCodecContext.thread_safe_callbacks. Starting with
>  LIBAVCODEC_VERSION_MAJOR=60, user callbacks must always be
>  thread-safe when frame threading is used.

The way I understand transcoding is single threading ... do you agree? 
is that enough to say: transcoding is 'thread-safe'?

**Comment by Flole998** [comment]
No, the functions called need to be thread safe, this is not enough at all. It needs further investigation as to why this was added.

**Comment by uknunknown** [comment]
That line came in this large update:
https://github.com/tvheadend/tvheadend/commit/014bb9505e1d7eb6e37e10931dd89ab3b1a0dc01#diff-a7125792d052aafcfb4384307fbac0183577ddd055a12500d0db5e4c829aee01

**Comment by uknunknown** [comment]
@gene-git I assume you are using an Intel platform, please confirm what CPU you have?
Also make sure you have Intel drivers installed and GuC fw enabled, a good source of info is:
https://tvheadend.org/boards/4/topics/48572
Make sure dmesg will show that iGPU FW is loaded (and kernel is tainted).

**Comment by gene-git** [comment]
CPU is old, but transcoding has been working fine for ages using older tvheadend.
The above errors are from the dev_ffpmeg6 branch when installed it on same machine as a test.

cpu:

      Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz
      vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.0 ()
     00:02.0 VGA compatible controller [0300]: Intel Corporation Iris Graphics 540 [8086:1926] (rev 0a)

intel media driver

    local/intel-media-driver 23.1.0-1
    Intel Media Driver for VAAPI — Broadwell+ iGPUs

I never had guc installed and its not now. Some of the stuff on the linked page is a bit X11 and desktop specific, and there is no X11 installed on this machine.

I am happy top continue testing now and again as things get fixed.

thanks again!

gene

**Comment by gene-git** [comment]
I noticed one more error with dev_ffmpeg6 as below:

    libav: AVCodecContext: Invalid frame dimensions 0x0.

**Comment by uknunknown** [comment]
> i5-6260U CPU

I don't think this SKL iGPU support hevc encoding. Can you run `vainfo` and post the results?
Can you check if H264 works? (most likely you have H264).

> libav: AVCodecContext: Invalid frame dimensions 0x0.

I get those errors all the time :( ... I think are related to how the encoding was done by your provider.

**Comment by Saentist** [comment]
> > i5-6260U CPU
> 
> I don't think this SKL iGPU support hevc encoding. Can you run `vainfo` and post the results? Can you check if H264 works? (most likely you have H264).

yes it support

> > libav: AVCodecContext: Invalid frame dimensions 0x0.
> 
> I get those errors all the time :( ... I think are related to how the encoding was done by your provider.

This is from too short analyzer probe time

**Comment by gene-git** [comment]
> Can you check if H264 works? (most likely you have H264).

vainfo: VA-API version: 1.18 (libva 2.17.1)
vainfo: Driver version: Intel iHD driver for Intel(R) Gen Graphics - 23.1.0 ()
vainfo: Supported profile and entrypoints
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileNone                   :	VAEntrypointStats
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointFEI
      VAProfileH264Main               :	VAEntrypointEncSliceLP
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointFEI
      VAProfileH264High               :	VAEntrypointEncSliceLP
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointVLD
      VAProfileJPEGBaseline           :	VAEntrypointEncPicture
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointFEI
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSliceLP
      VAProfileVP8Version0_3          :	VAEntrypointVLD
      VAProfileVP8Version0_3          :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointVLD
      VAProfileHEVCMain               :	VAEntrypointEncSlice
      VAProfileHEVCMain               :	VAEntrypointFEI

**Comment by gene-git** [comment]
I will retry with the dev_ffmpeg6 branch build and report back now that all configs point h264 profile.

**Comment by gene-git** [comment]
2 questions:

 - does tvheadend run vainfo to determine available stream profiles - the drop down lists h265 and h264 when h265 is not available.

- probably my own fault, but is there any way to make tvhmeta less verbose when it fails - i have a ton of these:
    
            spawn: Traceback (most recent call last):
            spawn:   File "/usr/bin/tvhmeta", line 461, in <module>
            spawn:     process(sys.argv[1:])
            spawn:   File "/usr/bin/tvhmeta", line 456, in process
            spawn:     tvhmeta.fetch_and_persist_artwork(opts.uuid, opts.force_refresh, opts.modules_movie, opts.modules_tv)
            spawn:   File "/usr/bin/tvhmeta", line 228, in fetch_and_persist_artwork
            spawn:     recjson = self.request("api/idnode/load", data)


Looks like python so shouldn't be too hard to make it catch the exception and exit gracefully instead of log splats.

**Comment by Saentist** [comment]
> * does tvheadend run vainfo to determine available stream profiles - the drop down lists h265 and h264 when h265 is not available.

```
VAProfileHEVCMain : VAEntrypointVLD
VAProfileHEVCMain : VAEntrypointEncSlice
VAProfileHEVCMain : VAEntrypointFEI
```
HEVC = H265

no It not run VAINFO, guess use ffmpeg libs for this
https://trac.ffmpeg.org/wiki/Hardware/VAAPI
https://trac.ffmpeg.org/wiki/HWAccelIntro

**Comment by gene-git** [comment]
@Saentist 

thanks that helped - so dropdown reflects whats available (at least according to ffmpeg).

And I missed it in the list this time - but you're right it does support h265 - so it was actually okay to use it - 
I'll put default profile back to h265.

**Comment by uknunknown** [comment]
a lot of messages ... so takeaway:
1. SKL has HEVC (h265) encoding (sorry ... my bad). --> we have to see why is not working.
2. you tested H264 and works. (please confirm!).

tvh is showing all encoders that you compiled for (is not checking that HW is supporting those encoders). You will have the surprise that newer iGPUs are not supporting vp8_vaapi encoder (for example), you will still see it on the list.

**Comment by gene-git** [comment]
I only have 2 choices for hw:

     webm_vp9_vaapi_hw
     h265_vaapi_hw

I changed to vp9 one.

I also edited my tvhmeta fix above to be quieter -  am testing that code as well.

**Comment by uknunknown** [comment]
@gene-git can you record with DVR a short clip of 30sec, using 'pass' in order for me to repro your problem? 

> I only have 2 choices for hw:

I think you are in the wrong menu. You need to add a 'codec profile' in codec profiles.
After that you can use it in Stream Profile.
codec_profile

**Comment by gene-git** [comment]
The codec was already defined and associated with that stream profile - is this not ok?


image

**Comment by gene-git** [comment]
> @gene-git I made a small change ... can you check again dev_ffmpeg6 with hevc?

Will build and test today. Thanks!

**Comment by mralapete** [comment]
Guys I’ve been watching this PR with interest. I’m using the latest Ubuntu 22.04 lts and have read the attached caveats. Are you guys compiling on Arch Linux with comes with FFMPEG 6. https://ubuntuhandbook.org/index.php/2023/03/ffmpeg-6-0-released-how-to-install-in-ubuntu-22-04-20-04/amp/

**Comment by gene-git** [comment]
>  Are you guys compiling on Arch Linux
Yes - on arch the base ffmpeg is 6.0.5 though ffmpeg5 is also available for older not-yet-updated apps.

**Comment by uknunknown** [comment]
> Are you guys compiling on Arch Linux with comes with FFMPEG 6

I am using Ubuntu 22.04 for my tests.

**Comment by mralapete** [comment]
> > Are you guys compiling on Arch Linux with comes with FFMPEG 6
> 
> I am using Ubuntu 22.04 for my tests.

Have you installed FFMPEG 6 in Ubuntu 22.04 in order to facilitate these tests

**Comment by uknunknown** [comment]
> Have you installed FFMPEG 6 in Ubuntu 22.04 in order to facilitate these tests

No. I didn't install any ffmpeg on OS. I compiled static ffmpeg using `./Autobuild.sh`

@Flole998 I hope you don't mind we a going a little off topic :( . Let me know if we should move those discussions on forum space.

**Comment by gene-git** [comment]
I am still running out of uknunknown/tvheadend/ dev_ffmpeg6 branch.
Any thoughts on when you may merge this back into the regular tvheadend/tvheadend  repo?

thanks!

**Comment by uknunknown** [comment]
@Flole998 I don't know how to help/unblock this; All I can think of is to add a config 'ffmpeg6' (default: no) that can be enabled with --enable-ffmpeg6. I can print some warning also that this feature is still in development. Only the users that know about this config and accept the risk will compile with ffmpeg6. Let me know your opinion.

**Comment by mralapete** [comment]
> @Flole998 I don't know how to help/unblock this; All I can think of is to add a config 'ffmpeg6' (default: no) that can be enabled with --enable-ffmpeg6. I can print some warning also that this feature is still in development. Only the users that know about this config and accept the risk will compile with ffmpeg6. Let me know your opinion.

Why are you so desperate to get this PR into the master branch. Surely you can continue using your own branch.

**Comment by uknunknown** [comment]
> Why are you so desperate to get this PR into the master branch. Surely you can continue using your own branch.

this branch already has conflicts ... slowly this will become outdated.

**Comment by uknunknown** [comment]
I opened a forum thread (to move discussions on forum): https://tvheadend.org/boards/5/topics/49793

**Comment by gene-git** [comment]
I'm really not sure why you don't push everything to master branch honestly - having patches is a bit unpleasant.

We should use git not standalone patches. 
We are in this spot precisely because this is not yet merged into master and so things are diverging.

I agree with @mralapete that the best option is:

   - merge all ffmpeg6 into master branch

If you really, really want to keep a separate branch for ffmpeg6 for some reason ( unclear why tbh),  then second best option would be:

  - create branch 'master-ffmpeg6' 
    Ensure this branch keeps in sync with master by pulling and merging any changes from master.
    Merge this back into master when you're comfortable and delete this branch.

please let's avoid standalone patches. just my view of course :)

**Comment by Flole998** [comment]
In order to get this merged the code needs to be checked to make sure it's threadsafe. Simply assuming that it is (after someone previously decided it isn't) will cause all sorts of issues.

**Comment by gene-git** [comment]
> threadsafe

@Flole998 for sure hat makes sense - so maybe we can use a  master-ffmpeg6 branch until such time as folks are comfortable merging it into master.

**Comment by Flole998** [comment]
Or someone goes through the code to see *why* it was marked as non-threadsafe previously and what needs changing. Sooner or later that needs to be done anyways.

**Comment by pimzand** [comment]
I'm using Fedora 38 with rpmfusion, which comes with ffmpeg 6.
I could compile and and use the master branch using ffmpeg 6 dynamically, without this PR by just disabling vaapi.
Have been using this for some time without issues.

**Comment by DoStRu** [comment]
I'm using the latest Ubuntu 23.10 which uses FFMPEG 6 and installing ffmpeg-5.1.3 is not possible due to package dependencies. Compiling TVheadend gives an error:
**./libavcodec/x86/mathops.h: Assembly messages:
./libavcodec/x86/mathops.h:125: Error: operand type mismatch for "shr"
make[2]: *** [ffbuild/common.mak:81: libavformat/adtsenc.o] Error 1
make[2]: exit directory "/root/DVB_TBS/src/tmp/tvheadend/build.linux/ffmpeg/ffmpeg-5.1.3"
make[1]: *** [Makefile.ffmpeg:693: /root/DVB_TBS/src/tmp/tvheadend/build.linux/ffmpeg/ffmpeg-5.1.3/.tvh_build] Error 2**

**Comment by mralapete** [comment]
Solution 1 https://tvheadend.org/boards/5/topics/50783

Solution 2 Try using Ubuntu 22.04 LTS

**Comment by gene-git** [comment]
Yeh for some reason tvheadend is very lagged.  ffmpeg 6 has been default for long time on systems I use too.

@uknunknown fork has been working fine for months here. Maybe try that

   https://github.com/uknunknown/tvheadend

And perhaps one day can switch back if this ever gets updated to work with 6.x which was released 9 months ago now,.

**Comment by DoStRu** [comment]
The code from the source https://github.com/uknunknown/tvheadend under Ubuntu 23.10 compiles with the error:
**./libavcodec/x86/mathops.h:125: Error: operand type mismatch for "shr"
make[2]: *** [ffbuild/common.mak:67: libavformat/adtsenc.o] Error 1
make[2]: exit directory "/root/DVB_TBS/src/tmp/tvheadend/build.linux/ffmpeg/ffmpeg-4.4.3"
make[1]: *** [Makefile.ffmpeg:694: /root/DVB_TBS/src/tmp/tvheadend/build.linux/ffmpeg/ffmpeg-4.4.3/.tvh_build] Error 2
make[1]: exit from the directory "/root/DVB_TBS/src/tmp/tvheadend"
make: *** [Makefile:855: /root/DVB_TBS/src/tmp/tvheadend/build.linux/ffmpeg/build/ffmpeg/lib/libavcodec.a] Error 2**

As I see, an even more outdated version of ffmpeg-4.4.3 is used here

Check out my temporary solution here - https://tvheadend.org/boards/5/topics/50783
I described how you can install a DEB package by trickery on Ubuntu 23.10. To do this I had to extract the old libraries from the Ubuntu 23.04 packages for ffmpeg 5 and install them separately. Next, I rebuilt the DEB package with the dependencies changed.

**Comment by mralapete** [comment]
I think it’s time this issue was resolved if it’s at all possible .Using Ubuntu 22.04 LTS obviously I haven’t come across this issue but now that it’s causing an issue in Ubuntu 23x and there’s an impending LTS in 2024 we will start seeing a lot more reported issues as many users tend to use an LTS version of the OS for stability purposes.

@uknunknown have you been able to resolve this PR to any level of satisfaction so we can push on with it.

**Comment by Lamarqe** [comment]
From here: https://patchwork.ffmpeg.org/project/ffmpeg/patch/20201029140122.10411-1-anton@khirnov.net/#60116
I can see that the parameter in doubt is about the implementation of the get_buffer2() method:

```
> They add considerable complexity to frame-threading implementation,
> which includes an unavoidably leaking error path, while the advantages
> of this option to the users are highly dubious.
> 
> It should be always possible and desirable for the callers to make their
> get_buffer2() implementation thread-safe, so deprecate this option.
> ---
> Postponed the removal until major 60, also documented this explicitly in
> APIchanges, so users can test for it.
```

The tvheadend implementation defines:
`avctx->get_buffer2 = vaapi_get_buffer2;`

With vaapi_get_buffer2 looking like the following:

```
static int
vaapi_get_buffer2(AVCodecContext *avctx, AVFrame *avframe, int flags)
{
    if (!(avctx->codec->capabilities & AV_CODEC_CAP_DR1)) {
        return avcodec_default_get_buffer2(avctx, avframe, flags);
    }
    return av_hwframe_get_buffer(avctx->hw_frames_ctx, avframe, 0);
}
```

So we rely on the implementation of avcodec_default_get_buffer2() and av_hwframe_get_buffer().
Both methods are part of ffmpeg, which is the component that exactly removed the option to have a thread-unsafe implementation.

From my perspective, the assumption that the removal of the parameter is correct, is valid.

If we want to be overly correct, we could safeguard this call with +#if LIBAVCODEC_VERSION_MAJOR < 60, but even that should not be necessary, as this property is deprecated in ffmpeg already since multiple longer time.

**Comment by Flole998** [comment]
Sounds reasonable! Thank you! This needs to be rebased then so we can see if it builds on all targets. @uknunknown Could you take care of that please? Other than that it should be good to merge then.

**Comment by wuppiwuppi** [comment]
Any plan on how to go on here?

**Comment by CvH** [comment]
> Any plan on how to go on here?

add the needed changes for ffmpeg 6.0.1 here
https://github.com/tvheadend/tvheadend/pull/1573

**Comment by chewitt** [comment]
Closing as superseded by #1573

**Pull request closed without merging**
