### PR TITLE
add low power to h264_vaapi

### PR DESCRIPTION
**Pull request by alingherghescu**
add low power to h264_vaapi

### CODE REVIEW

**Comment by Flole998** [comment]
Thanks, there's just a small thing I noticed. Please have a look and if you agree adjust it accordingly (don't forget to squash your commits if there are multiple ones, or just amend to your previous commit), but maybe I just have a wrong impression of how it looks like in the UI?

**Comment by alingherghescu** [comment]
I documented the UI part in:
https://tvheadend.org/issues/6224?next_issue_id=6223&prev_issue_id=6225
I only cut the Expert Settings. 
I can send you a full window too ... for the big picture.

**Comment by alingherghescu** [comment]
UI_full

**Comment by alingherghescu** [comment]
From your comment is not clear if you want me to change something ... if Yes: I don't understand what to change. I am not versatile in github :( .

**Comment by Flole998** [comment]
I left a few comments in the code, you should be able to see those.

Also if you want an option to enable/disable something use a checkbox and not a text field with 0/1.

**Comment by alingherghescu** [comment]
UI updated to checkbox.
I don't know how to see your comments :( ... if you think is the right thing ... do the change.
 
UI_full

**Comment by Flole998** [comment]
Please remove the "(disabled)" from the label. Also please squash your commits together.

**Pull request closed without merging**
