### PR TITLE
[do not merge] Tvh website/forum down

### PR DESCRIPTION
**Pull request by CvH**
Currently the tvh website is down due some redmine error. Are you aware and can you fix it (no idea who has access to the servers)?
Sorry for hijacking the prs but IRC (empty) and gh Issues are not enabled :)

### CODE REVIEW

**Comment by mralapete** [comment]
That’s the problem. Not having a list of mods contact details outside of the TVH forum poses a problem which has now been highlighted in this instance. I did highlight it elsewhere hoping that TVH mods were looking in but nothing so far.

**Comment by ProfYaffle** [comment]
I suspect @andoma (or perhaps @mpmc ) is the likely saviour here, if anyone...

**Comment by mralapete** [comment]
@Flole998 just wondering if you are aware of this.

**Comment by Flole998** [comment]
I am aware but I don't have access either.

**Comment by CvH** [comment]
> I am aware but I don't have access either.

an idea who has access ? idk maybe @perexg still has some kind of access

**Comment by ProfYaffle** [comment]
Digging up other ghosts, paging @adamsutton just in case he has any thoughts either.

I have an offer from someone who could host the forum instead of the current Redmine if that helps, but we'd still ideally resurrect this one first, and would need to know more about e.g. DNS ownership (looks like tvheadend.org is registered until June 2024, so ...).

**Comment by jansohn** [comment]
Or open up Github issues section instead? Not sure if anybody active has the rights to do so...

**Comment by vascobraga41** [comment]
With all the permissions problem, even here on GitHub, maybe some of the active members should fork and have full control from now on. This is a ticking time bomb.

**Comment by mpmc** [comment]
Sadly @andoma is the only one who can fix this issue.

**Comment by Flole998** [comment]
I don't really see the point of enabling issues here. People will report issues and nobody cares. There's just no point with no developers.

I could host Redmine aswell, but DNS is indeed the biggest issue here. Ideally the whole Database would be transferred aswell.

**Comment by jansohn** [comment]
So we don't need a forum either, right?

**Comment by CvH** [comment]
> I could host Redmine aswell

why repeat the current issue, just do it completely at github and spread the rights for it to some trustworthy persons, done

> I don't really see the point of enabling issues

An off platform issue tracker and a off platform forum that requires an additional account is also not really a way forward :)
Instead of spreading everything out to make it as complicated as possible, just concentrate it on a single platform where everyone has easy access and requires NO maintenance and still works if one "admin" goes awol.

**Comment by Flole998** [comment]
But why should there be an issue tracker in the first place? There is no support, nobody who cares and experience shows people will just open issues for old versions and whatnot that need to be closed then. If this project would be actively maintained that would be a different story. A Forum/GitHub discussions would be the only thing that makes sense IMO.

**Comment by mralapete** [comment]
@CvH i reported the TVH forum outage here 3 days ago in an open PR hoping someone might react to it https://github.com/tvheadend/tvheadend/pull/1569#issue-1977698865
Clearly not. 

I then reluctantly posted on the LibreELEC forum again with little or no interest shown until you came along and commented along with some other idiot, not you of course, at which stage the moderator locked the thread for some reason 
https://forum.libreelec.tv/thread/27692-tv-headend-forum-down/

Well it appears from the general lack of positive response on who can remedy the problem the TVH forum is well and truly screwed. I can’t believe the forum just stumbled along for what looks like the last 5 years without any form of control on content or administration. The Marie Celeste of the forum world.

Not that anyone has commented so far but has anyone considered that the forum has been hacked and the possibility that personal information is floating around in the ether for all to see. 

I’d strongly recommend that we reach out to the original five named individuals on the project and see if they can either re establish connectivity with the forum, bring it back up or completely remove it permanently.

If indeed TVH is dead why bother with any new builds. I don’t see the point. On the other hand if people are genuinely interested in taking the project further open up the administration of both the forum and github to a number of well intentioned and experienced individuals to achieve this. You cannot possibly leave a project like this in the hands of one individual.

**Comment by CvH** [comment]
@Flole998 
> A Forum/GitHub discussions would be the only thing that makes sense IMO.

makes sense

I would just really advocate that you (tvh "team") move all the stuff to github instead to some 3rd party service nobody has any access. There is basically zero maintenance needed and its easy to share rights and even to hand over to a new one. Worst case the github support is also available if something goes wrong.

Wiki etc could easily done at github too without any overly invested time.
Even a website (if the dns get solved) could be hosted at github easily.
We at libreelec.tv do the same due named benefits.

**Comment by ProfYaffle** [comment]
@CvH Please don't underestimate "we" - there is no "we" any more, that's the problem.

I'm in touch with the LE team, and they can help with hosting because of the large LE/Tvh userbase. We still have practicalities of even redirecting a DNS record we can't access, let alone moving text over that isn't available without the Wayback Machine.

**Comment by mralapete** [comment]
> @CvH Please don't underestimate "we" - there is no "we" any more, that's the problem.
> 
> I'm in touch with the LE team, and they can help with hosting because of the large LE/Tvh userbase. We still have practicalities of even redirecting a DNS record we can't access, let alone moving text over that isn't available without the Wayback Machine.

I personally wouldn’t be in favour of moving TVH business to a front end specific forum like LibreELEC. Best if it could somehow retain its independence on its own platform like the GitHub here for the moment.

As was mentioned above a discussions section could be opened on this Github. I imagine TVH users/potential users will in time find that section. Remember there are other front ends that TVH users employ and for the amount of traffic that currently pass through the TVH forum this GitHub would be more than able to cope.

In the meantime If we do manage to recover the TVH forum we can request that admin privileges are entrusted to couple of reliable users.

**Comment by Flole998** [comment]
> In the meantime If we do manage to recover the TVH forum we can request that admin privileges are entrusted to couple of reliable users.

I've tried that before, no luck. Nobody was able to ban spammers, all we could do was delete the posts/comments and hope they don't post again.

**Comment by ProfYaffle** [comment]
> I personally wouldn’t be in favour of moving TVH business to a front end specific forum like LibreELEC. Best if it could somehow retain its independence on its own platform like the GitHub here for the moment.
> 

"Help with" doesn't mean "merge" - options, that's all, if we can wake the dead.

**Comment by th0ma7** [comment]
I know, I know... TVH is dead, long live TVH!  I've been following-up this project since the last few years and maintaining the SynoCommunity build.

Thing is, there's been more commits in 2023 than in the last 2-3 previous years...
```
$ git log --decorate --oneline --graph --since "1 year" | wc -l
110
```
Playing a bit with this, approximates using years from now, 2023 has been more flourishing than the last 3 years :
- **2023**: 110 commits
- **2022**: 68 commits
- **2021**: 67 commits
- **2020**: 62 commits
- **2019**: 334 commits

In cahos opportunities... using this as a mean to re-opening the project more widely to new contributors may be an idea?  Who knows who might step up and help... 

Just my two cents ...

**Comment by mralapete** [comment]
> > In the meantime If we do manage to recover the TVH forum we can request that admin privileges are entrusted to couple of reliable users.
> 
> I've tried that before, no luck. Nobody was able to ban spammers, all we could do was delete the posts/comments and hope they don't post again.

Not sure what method you used to make contact about this issue but I sent a message to one of the original project contributors and here’s the result
https://tvheadend.org/

**Comment by Flole998** [comment]
Maybe you can ask about the "permission problem" aswell so we might be able to get that fixed aswell?

**Comment by ProfYaffle** [comment]
> > > In the meantime If we do manage to recover the TVH forum we can request that admin privileges are entrusted to couple of reliable users.
> > 
> > 
> > I've tried that before, no luck. Nobody was able to ban spammers, all we could do was delete the posts/comments and hope they don't post again.
> 
> Not sure what method you used to make contact about this issue but I sent a message to one of the original project contributors and here’s the result https://tvheadend.org/

Congratulations on that. Might be helpful to know who you managed to get hold of so we've at least a chance of a conversation.

**Comment by vascobraga41** [comment]
I don't see the problem if some team like Libreelec puts their weight behind this. The important part is not to lose tvheadend and its history. It's mind-blowing and at the same time somehow expected that such an important project is in a limbo.
I have a bit of PTSD because of the problems the community went through when afl1 vanished. So much knowledge lost and no one could really replace him.

**Comment by mralapete** [comment]
> Maybe you can ask about the "permission problem" aswell so we might be able to get that fixed aswell?

Yes I included that request in my message. For the moment at least the forum is back on line so let’s all start interacting with it. 

Many users visit the forum for the first time requesting assistance with TVH. Maybe we could all contribute a little more in this area. 

Just to clarify what level of administrative access do you have to both the forum and the github. Clearly someone along the chain granted you certain privileges.

**Comment by mralapete** [comment]
> I don't see the problem if some team like Libreelec puts their weight behind this. The important part is not to lose tvheadend and its history. It's mind-blowing and at the same time somehow expected that such an important project is in a limbo.
> I have a bit of PTSD because of the problems the community went through when afl1 vanished. So much knowledge lost and no one could really replace him.

Most of the applications that interact with TVH already have a section on TVH in their respective forums which I imagine could be extended to cater for any additional input. 

It’s best if TVH remains neutral so no priority or favouritism is given to any individual application at a disadvantage to another. 

If you’re not already contributing to TVH both from a development and a support level why not join in and help improve the user experience.

**Comment by Flole998** [comment]
On this repo I have "full" access, but not on the other repos in the Tvheadend organization. Ideally someone would add me to the organization itself with higher privileges.

On the Forum/Issue Tracker I can access all the settings, edit posts, delete posts and so on, but I can't ban spammers. That is really annoying and something that should be addressed at some point because I am really tired of playing cat and mouse.

**Comment by mralapete** [comment]
> On this repo I have "full" access, but not on the other repos in the Tvheadend organization. Ideally someone would add me to the organization itself with higher privileges.
> 
> On the Forum/Issue Tracker I can access all the settings, edit posts, delete posts and so on, but I can't ban spammers. That is really annoying and something that should be addressed at some point because I am really tired of playing cat and mouse.

Obviously you must have had a direct line to the forum creators to be given those privileges. Did you loose contact with them at some stage.

While it’s best to keep admin privileges as tight as possible it’s never a good idea to leave the responsibility of moderation to one single individual. You can’t be watching the forum 24/7 and of course the spammers thrive on that fact. 

Might be an idea to take the discussion to the TVH forum now to try and establish if any other members have similar privileges to yourself and find out if they are actually interested in exercising those privileges. It’s neither fair nor sensible to leave those responsibilities solely to you.

We may also be able to establish if there are in fact any members genuinely interested in further developing TVH beyond changing a line or two of code.

**Comment by Flole998** [comment]
I can give other privileges on the Forum/issue tracker aswell, and I have done so in the past, but without banning the spammers it's just playing cat and mouse.

**Comment by mralapete** [comment]
> > I can give other privileges on the Forum/issue tracker aswell, and I have done so in the past, but without banning the spammers it's just playing cat and mouse.
> 
> Another reason for switching to GitHub discussions/issues? 😏

The problem with GitHub is the average TVH user is not a member nor would be particularly likely to join. The majority install TVH from a PPA and the format used in github is more directed towards the development world rather than the user world.

**Comment by Martii** [comment]
> The problem with GitHub is the average TVH user is not a member nor would be particularly likely to join

They might join.

> The majority install TVH from a PPA and the format used in github is more directed towards the development world rather than the user world.

Most of us don't build from source *(unless we have a lot of spare time or extreme dedication/experience)* and use a PPA. However discussions can be tailored from issues like we have done on OUJS. See https://github.com/OpenUserJS/OpenUserJS.org/issues/new/choose . The available GitHub *(GH)* Actions as well can be customized. An Issue can always be "promoted" to a discussion as well... some nice features that GH has now. We're still contemplating discussions as we predate that feature and use labels currently.

As per the discussion of maintainers needed and such I hope that this project does survive and can find a happy medium. :smiley:

**Comment by CvH** [comment]
> The problem with GitHub is the average TVH user is not a member nor would be particularly likely to join.

If no one cares about the forum (no time, no rights ...) and it just creates overhead it could be "fixed" with switching to gh forum. That sounds meh but it is sadly the truth, you get less worthless feedback at github because the typical "i have no idea what is going on" user won't interact at github that frequently.  So in general you get "better" feedback.

Just a small side info, the current used redmine version is ~4 years old and had no updates in between (needs time + access, likely not happening).
A quick look at https://www.redmine.org/projects/redmine/wiki/security_advisories sparks joy.
I would bet the server where the stuff is hosted is similar outdated and unmaintained.

**Comment by jansohn** [comment]
> The problem with GitHub is the average TVH user is not a member nor would be particularly likely to join. The majority install TVH from a PPA and the format used in github is more directed towards the development world rather than the user world. 

Why would the average TVH user create an account for the forum but not for GitHub? Doesn't make any sense in my opinion?

I even think that it's more likely to attract more potential developers if discussions/issues are tracked on the same platform...

**Comment by mralapete** [comment]
> > The problem with GitHub is the average TVH user is not a member nor would be particularly likely to join. The majority install TVH from a PPA and the format used in github is more directed towards the development world rather than the user world.
> 
> Why would the average TVH user create an account for the forum but not for GitHub? Doesn't make any sense in my opinion?
> 
> I even think that it's more likely to attract more potential developers if discussions/issues are tracked on the same platform...

You’re missing the point. It’s a forum that usually attracts users with queries. Why would a user need a github account. A simple install by adding a PPA to their distro is all they need. That’s certainly how it appears to be done over the last couple of years. Of course if you’re building your own the GitHub is the place to be.

**Comment by mralapete** [comment]
> > The problem with GitHub is the average TVH user is not a member nor would be particularly likely to join. The majority install TVH from a PPA and the format used in github is more directed towards the development world rather than the user world.
> 
> Why would the average TVH user create an account for the forum but not for GitHub? Doesn't make any sense in my opinion?
> 
> I even think that it's more likely to attract more potential developers if discussions/issues are tracked on the same platform...

For the moment, the TVH forum is back on line so that’s that problem solved for users dropping by with their queries. Maybe those who responded here could assist in answering those queries and generate some interest in it.

I imagine the GitHub discussion section could be expanded too so all bases are covered. Other than that, the future of the TVH forum and TVH itself can be discussed at length over on the TVH forum where everyone can contribute.

**Comment by ProfYaffle** [comment]
This is an interesting conversation, and perhaps there's more life here than we thought. However, it's partly all academic unless people can get access to what 's needed.

@mralapete in case you missed the question above - who did you manage to get hold of, and how? I can see pretty much all the old project leaders have been tagged here and/or on Twitter, so you obviously had success through some other route. Getting a conversation underway with them to gain better access might be a starting point.

**Comment by chewitt** [comment]
@mralapete As someone interested in ensuring TVH continues and perhaps improves I'd be interested in having a chat. I can be reached by email (chewitt@ Kodi domain) or pm me on IRC (chewitt in #kodi or #libreelec).

**Comment by mralapete** [comment]
> This is an interesting conversation, and perhaps there's more life here than we thought. However, it's partly all academic unless people can get access to what 's needed.
> 
> @mralapete in case you missed the question above - who did you manage to get hold of, and how? I can see pretty much all the old project leaders have been tagged here and/or on Twitter, so you obviously had success through some other route. Getting a conversation underway with them to gain better access might be a starting point.

What do you need access to. All the detail you need is contained in the TVH forum. 

My goal was to get the TVH forum back on line which has now happened. After that it’s up to the current crop of members to decide what direction to take TVH in, both from a developer and user point of view. Any information you require is already contained in the forum. 

At no stage did I say I got any response from anyone but after sending out requests through contacts the TVH forum reappeared back in line. That’s all I can tell you.

**Comment by ProfYaffle** [comment]
@mralapete I'm not after any forum information - I merely thought that you'd successfully contacted someone, but it appears you sent a message (as did many others) and then the forum came back - correlation is not causation, sadly.

So we're none the wiser as to who might have seen what messages on what platform - if, indeed, anyone did, since it's always possible that a job restarted automatically, something was rebooted, andoma noticed independently, and so on. Boooo.

I think all roads still lead back to @andoma if we've any hope of keeping things moving. Either that or new forks, a new domain, new forum, and lots of wiki-scraping.

**Comment by mralapete** [comment]
> @mralapete I'm not after any forum information - I merely thought that you'd successfully contacted someone, but it appears you sent a message (as did many others) and then the forum came back - correlation is not causation, sadly. Thanks for giving it a go, though.
> 
> So we're none the wiser as to who might have seen what messages on what platform - if, indeed, anyone did, since it's always possible that a job restarted automatically, something was rebooted, andoma noticed independently, and so on. Boooo.
> 
> I think all roads still lead back to @andoma if we've any hope of keeping things moving. Either that or new forks, a new domain, new forum, and lots of wiki-scraping.

Sure. 

Whoever’s message got to where it should go the forum is back on line. That’s all that matters here. Nothing stopping anyone grabbing a copy of it off line for reference and even forking the project as you say. 

The project had basically faded away after the last official release 6 years ago and nobody took up the slack in the meantime. That’s a lifetime in technology terms. Who knows, maybe after this event it will again get a bit of traction again. Personally speaking, TVH does what I need it to do. Who knows that may well change. Good luck with whatever you decide.

**Comment by chewitt** [comment]
To me it looks like there are concerns around owernship and control, transparency, and communication: none of which are uncommon in projects that start out with a single contributor then follow the well-troden BDFL route towards a more team oriented structure. The main questions I have are:

- Who (or what entity) currently owns and manages the TVH .org domain?
- Who are the current GitHub organisation owners?
- What infrastructure does the project have and depend upon?
- How is the project funded?
- How are funds held and accounted for?
- What's the current balance and burn rate?
- Current state of the GPLv3 to GPLv2 relicense effort?

Some of those topics are discussed (or deflected) in forum posts. However most of the threads and responses are a decade old and the noble intentions of the past may not be relevant or true today. Knowing the current status quo on those topics would be informative.

To be clear, I'm not interested in trying to take-over, fork, or run any more projects (LibreELEC is enough) and I don't write proper code so have no opinion on codebase/development. However, reading old posts I see lots of familiar effort and organisational issues, and I know first-hand what's worked/not-worked for several similar-size or similar-origin FOSS projects over the last decade. The main skills I have to offer are around the boring but essential back-office stuff that allows a project to function, plus sysadmin or secadmin work. If I can help .. I'd be keen to know how?

CH.

**Comment by mralapete** [comment]
> To me it looks like there are concerns around owernship and control, transparency, and communication: none of which are uncommon in projects that start out with a single contributor then follow the well-troden BDFL route towards a more team oriented structure. The main questions I have are:
> 
> * Who (or what entity) currently owns and manages the TVH .org domain?
> * Who are the current GitHub organisation owners?
> * What infrastructure does the project have and depend upon?
> * How is the project funded?
> * How are funds held and accounted for?
> * What's the current balance and burn rate?
> * Current state of the GPLv3 to GPLv2 relicense effort?
> 
> Some of those topics are discussed (or deflected) in forum posts. However most of the threads and responses are a decade old and the noble intentions of the past may not be relevant or true today. Knowing the current status quo on those topics would be informative.
> 
> To be clear, I'm not interested in trying to take-over, fork, or run any more projects (LibreELEC is enough) and I don't write proper code so have no opinion on codebase/development. However, reading old posts I see lots of familiar effort and organisational issues, and I know first-hand what's worked/not-worked for several similar-size or similar-origin FOSS projects over the last decade. The main skills I have to offer are around the boring but essential back-office stuff that allows a project to function, plus sysadmin or secadmin work. If I can help .. I'd be keen to know how?
> 
> CH.

No doubt with your involvement in LibreELEC you’ll be acutely aware of the politics involved in open source projects vis-a-vis OpenELEC/CoreELEC/LibreELEC. 

Nothing is ever as straightforward as it seems. Among other problems and in certain cases inflated egos creep into the project with certain individuals trying to assert control. There’s no obvious signs of this in the TVH project, certainly not up to the last official release.

If you’ve followed the TVH release history in reverse you’ll quickly see name’s emerging and I’ve no doubt they’ll be the people to comment on the situation. They may choose not to correspond or communicate on this as is their right to do so. Likewise individuals commenting here have chosen not to comment in the TVH forum. Therein lies the problem.

**Comment by DeltaMikeCharlie** [comment]
> I can give other privileges on the Forum/issue tracker aswell, and I have done so in the past, but without banning the spammers it's just playing cat and mouse.

@Flole998 - Do you have an option to configure the forum/issues so that the first post of a newly registered user needs to be approved by a moderator?  I am a member of at least one forum that does this.

I understand that it would inconvenience authentic first-timer users in search of support, however, it could help with the spamming problem.

Also, when you mention "banning the spammers", how would that work?  If you ban based on email address, then they just go and get another.  If you ban based on IP address, then next time they just post from the next café down the street with free wifi.

**Comment by Flole998** [comment]
That's not an option I can configure.

I would like to ban the user account in such a case. Yes, they can generate a new one, but deleting posts while they create new ones is just silly. This needs to be sorted out somehow.

**Comment by DeltaMikeCharlie** [comment]
> I would like to ban the user account in such a case.

@Flole998 - When you say 'ban', are you referring to disabling or deleting the account that is doing the spamming?

**Comment by Flole998** [comment]
Yes exactly, disabling or deleting, either option would be fine.

**Comment by DeltaMikeCharlie** [comment]
@Flole998 - I’m not trying to be insulting here, I’m just trying to collect some data and suggest some ideas.  Perhaps laying out what we know and what we don’t know could be helpful in moving forward.  There may be some overlap here with the questions that @chewitt has already asked.

Q1) Do you have sufficient access to the forum software to be able to backup/download the whole forum/issues database?

The ‘tvheadend.org’ domain seems to be held by a registrar called ‘Gandi SAS’.  They appear to be French.

The domain was last updated on 2023-06-16 and is due to expire on 2024-07-15.

Q2) Do you, or anyone that you have contact with, have control of the domain?
Q3) Do you know who paid Gandi for the last renewal?
Q3.1) Does the registrar just keep auto-charging the credit card that they have on record?
Q3.2) Could this registration be lost on 2024-07-15?

The name servers for ‘tvheadend.org’ are ‘grace.ns.cloudflare.com’ and ‘simon.ns.cloudflare.com.

tvheadend.org has 2 ‘A’ records: 104.21.22.193 and 172.67.206.223.

Both of these IP addresses seem to be part of AS13335 (Cloudflare, Inc.).

All of this points to ‘cloudflare.com’ as being the party that hosts the forum.

Q4) Have you, or anyone you have contact with, contacted Cloudflare to establish who ‘owns’ the TVH account with them?
Q5) Do you know who paid for the last Cloudflare renewal?

From here, one of two major possibilities may exist:
1) Cloudflare host a whole dedicated VM that runs the forum.
2) Cloudflare hosts the forum in a centralised multi-customer environment that they control.

Q6) Do you, or anyone you have contact with, know what the hosting arrangement with Cloudflare is?

If option 2) above, then perhaps you could approach Cloudflare and convince them that the account has been abandoned and allow you to take it over and manage the forum with full control.

Criteria for declaring abandonment could be something like the principal client username not having logged in for a number of years, etc.

If option 1) above, you would still have to convince Cloudflare that account has been abandoned and get control of the account.  I’m no expert on cracking root passwords, but if the VM is stored in a disk image file, then perhaps you could run up a new VM and mount the image elsewhere as a secondary disk and ‘see what you can find’.  At the very least, you should be able to get a full backup.

Perhaps you could ask Cloudflare to become a sponsor.  Place their logo prominently on the forum with slogans such as “Proudly hosted by Cloudflare” and “Supporting the open source community” plastered everywhere.

Unless you have control of the domain, moving to an alternate hosting service could be challenging.  Perhaps you could express to Gandi that you have interest in taking over the domain should it become available.  If the next payment is missed, then the project can buy (back) the domain and thus have control.

**Comment by mralapete** [comment]
Guys it may well be worth your while reading this if you have not already done so. Note the call out for volunteers for developing, documentation and support. Many promises but few if any came to fruition. In particular Adam Sutton made very clear his position at the  time so the writing was on the wall nearly a decade ago. At some stage the final disconnect took place and we as users find ourselves in the position we are in now. https://tvheadend.org/projects/tvheadend/news

Maybe if the users commenting here now could take the time to post their concerns on the future of the TVH project openly for all to discuss, while they still can I might add and while there participate a little more in forum activities who knows who maybe looking in.

**Comment by DeltaMikeCharlie** [comment]
I did some more investigating:

Some of the copyright statements include reference to the “Tvheadend Foundation CIC”.  There is also a posting on the TVH forum regarding this:  https://tvheadend.org/projects/tvheadend/wiki/Foundation

I went to the UK Government’s website to perform a search and it appears that the foundation was either not created or was created and dissolved.  In either case, it does not appear to exist today.

https://findthatcharity.uk/orgid/type/community-interest-company

I noticed that the WebUI ‘About’ page for TVH includes a link for donations that seem to be facilitated via PayPal.

https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=3Z87UEHP3WZK2

Knowing who owns or has control over this PayPal account could be useful.  It could still have a credit balance and may even be used to pay for domain hosting, etc, to this day.

**Comment by chewitt** [comment]
@DeltaMikeCharlie The UK foundation was never created (confirmed). Please drop me an email.

**Comment by Saentist** [comment]
> I did some more investigating:
> 
> Some of the copyright statements include reference to the “Tvheadend Foundation CIC”. There is also a posting on the TVH forum regarding this: https://tvheadend.org/projects/tvheadend/wiki/Foundation
> 
> I went to the UK Government’s website to perform a search and it appears that the foundation was either not created or was created and dissolved. In either case, it does not appear to exist today.
> 
> https://findthatcharity.uk/orgid/type/community-interest-company
> 
> I noticed that the WebUI ‘About’ page for TVH includes a link for donations that seem to be facilitated via PayPal.
> 
> https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=3Z87UEHP3WZK2
> 
> Knowing who owns or has control over this PayPal account could be useful. It could still have a credit balance and may even be used to pay for domain hosting, etc, to this day.

Maybe we should start with simple Topics in repository with missing,
currently is hard findable by keyword's. 
image
better looking as this
image
more Topics can be added ex: multicast input and output playlist output etc.

More popular repo more users eventually more developer's.
Donations can be also enabled in github platform

----
p.s. I'm a wiki editor in website

**Comment by DeltaMikeCharlie** [comment]
> Maybe we should start with simple Topics in repository with missing, currently is hard findable by keyword's.

@Saentist - This seems like a good idea, however: 1) What GitHub permissions are required to make this update?  2) Does anybody who is still working on the project have those permissions?

**Comment by Saentist** [comment]
> > Maybe we should start with simple Topics in repository with missing, currently is hard findable by keyword's.
> 
> @Saentist - This seems like a good idea, however: 1) What GitHub permissions are required to make this update? 2) Does anybody who is still working on the project have those permissions?

Someone say above that he have full permission on repo, he can do it https://github.com/tvheadend/tvheadend/pull/1569#issuecomment-1798739578
let's see is it possible.

**Comment by mralapete** [comment]
@Flole998 now that the forum is back on line this issue is resolved and could be closed now. If the participants want to continue the discussion they could do so on the TVH forum where everyone can participate.

**Comment by Flole998** [comment]
While closing this issue doesn't prevent future discussions here this is resolved now, even though nobody knows why/how this was fixed.

**Comment by mralapete** [comment]
Absolutely but where possible we should be pushing as much traffic to the forum as possible. I did correspond with a number of the original project creators and recommended that they grant you the access needed to put things back on track. I hope that is in order with you.

**Comment by perexg** [comment]
@Flole998 : You're manager of https://tvheadend.org/projects/tvheadend, so you should have enough permissions. I think that it was set a long time ago or someone else did it. Unfortunately, I cannot do more, because redmine is operated by Andreas Smas.

BTW: I added you to the admin group on github for this project now, too.

**Comment by Flole998** [comment]
Hi @perexg, nice to hear from you. I'm aware that I'm in the manager group but that only allows me to delete individual posts. What happened quite a few times already is, that I receive an E-mail about a new comment, I notice it contains a spam link and I'm looking at the user and I'm deleting the posts as new ones pop up. I think only Andreas can take additional actions to disable/ban users.

Thanks for adding me to that group, I've received a notification about that a while ago but nobody knew who did it.

**Comment by perexg** [comment]
> I notice it contains a spam link and I'm looking at the user and I'm deleting the posts as new ones pop up. I think only Andreas can take additional actions to disable/ban users.

I can also only delete posts. Perhaps, redmine does not allow to remove/ban users through the web interface in the standard installation. But as I wrote, I cannot do anything with it. Eventually, only Andreas can export database and change DNS to migrate the forum to another server.

**Comment by mralapete** [comment]
> > Perhaps, redmine does not allow to remove/ban users through the web interface in the standard installation.
> 
> I think that is only possible for "global admins", at least according to some documentation.
> 
> If there is indeed a migration or re-setup of the forum, would you like to be a part of it or have you decided to leave Tvheadend now forever?

Are you contactable directly. Just wanted to update you.

**Comment by Flole998** [comment]
You can reach me at flole@flole .de

**Comment by perexg** [comment]
> If there is indeed a migration or re-setup of the forum, would you like to be a part of it or have you decided to leave Tvheadend now forever?

I actually have no plans with tvheadend, but I'd like to stay as a "hidden" developer. Perhaps, I will revive, but I don't promise anything.

**Comment by chewitt** [comment]
We are in the process of disentangling the `tvheadend.org` domain from Andreas' accounts in Cloudflare and it looks like something broke in the process so the forum is currently offline. Nobody panic :)

**Comment by mralapete** [comment]
I doubt any panic will ensue. It may discommode the spammers though 😂

**Comment by chewitt** [comment]
@mralapete please drop me an email .. thx

**Comment by mralapete** [comment]
> @mralapete please drop me an email .. thx

To where ??

**Pull request closed without merging**
