### PR TITLE
Adding scrape for bg

### PR DESCRIPTION
**Pull request by zinonino**
Adding scrape for Episode, Season for Bulgarian lang.

### CODE REVIEW

**Comment by zinonino** [comment]
Yes, you right  "'кулинарно предаване, 3 епизода'" must not show, becasue "3 епизода'" mean will show 3 episodes, one  after follow by second and follow by third, 3 together,  not mean 3rd episode. I dont have idea how to miss only "епизода", but to stay "епизод", idk why catch "а" when, not put in file. If you have any idea is welcome. 
When try "([0-9]+) епизод ", not catch both, when try "([0-9]+) епизод" , catch both "епизода" and "епизод.

**Comment by azlm8t** [comment]
Ah, I understand now. So "3 епизода" could be for cartoons where it means 3 episodes of "Scooby Doo" are shown together in one broadcast 9.30am--11am. Thanks. I'll take another look in a couple of hours.

**Comment by azlm8t** [comment]
Try changing the last two lines in episode_num (and then re-running an OTA scan).
(I can't tell in my browser if it has pasted correct, so that is "cyrillic a").

`
      "episode_num": [
        "([0-9]+) серия",
        "еп. ([0-9]+)",
        "[, ] ([0-9]+) еп[.]",
        "[, ] еп.([0-9]+)",
        "([0-9]+) еп.[,]",
        "сериал[, ] еп.([0-9]+)",
        "епизод ([0-9]+)",
        "Епизод ([0-9]+)",
        "[, ] ([0-9]+) епизод([^а]|$)",
        "([0-9]+) епизод([^а]|$)"

    ],
`

**Comment by zinonino** [comment]
Thank you for  suggestion, now all work perfect, added also some new type of scrape, final must look this.

**Comment by zinonino** [comment]
bnt
episodes

Now waiting @perexg to merge to master.

**Comment by azlm8t** [comment]
Glad it works.

But, I don't think the "2018/19" lines are correct. (Though it will look ok in the EPG).
```
echo "сезон 1, епизод 13, драма, романтичен, САЩ, 2014" | egrep "сезон ([0-9]+)([^2018/19]|$)"   
```
==> "1," (one with a comma) but should be "1" (without comma).

Do you have an example of what you are trying to match / not match with that line? 

There examples I have are in tvheadend/support/testdata/eitscrape/bg.

**Comment by zinonino** [comment]
I try not match, because catch football season 2018/19 , and write like series, Look a pic.

image

**Comment by azlm8t** [comment]
OK, try this:
```
   "season_num": [
        "сезон ([0-9]{1,3})[^0-9]",
        "[, ] сезон ([0-9]{1,3})[^0-9]",
```
This means "3 digits only" (does not match 4 digits) so will work for 2019/2020 too.

**Comment by zinonino** [comment]
Now not catch all season, some catch, some missing.
missing
missing2

**Comment by azlm8t** [comment]
One final try:
```
"season_num": [
        "сезон ([0-9]{1,3})([^0-9]|$)",
        "[, ] сезон ([0-9]{1,3})([^0-9]|$)",
```

**Comment by perexg** [comment]
Merged.

**Comment by perexg** [comment]
e6a07318bf7c7dfd3609bc89dc733eb832fe24d0

**Pull request closed without merging**
