### PR TITLE
Revert to earlier FRITZ!-workaround

### PR DESCRIPTION
**Pull request by WereCatf**
The method suggested by perexg didn't actually work now that I had time to test it properly, it's still not adding pid 21 where it should be. My method, as inelegant as it may be, at least adds the pid there at all times.

### CODE REVIEW

**Comment by perexg** [comment]
OK. Reverted with small changes - d46b3c459cd7690847df1380a2cfbe625d174262 .

**Comment by StofLE** [comment]
I have FRITZ!WLAN Repeater DVB-C wich is shown in Windows or iOS-SAT>IP App. What to do that Tvheadend (I compiled newest version) recognize it?

**Comment by WereCatf** [comment]
StofLE: start tvheadend with the argument:
--satip_xml http://your.box.ip.address:49000/satipdesc.xml

That should bring it visible in tvheadend. If your box has multiple tuners in it you probably won't be able to use them simultaneously, though; with my box if one IP-address tries to use multiple tuners simultaneously it'll just stop responding to all the other streams other than the last one opened, ie. I can only use one tuner.

Wish I could point tvheadend to bind one tuner to one network interface and another tuner to another interface with another IP-address, then I could use multiple tuners.

**Comment by StofLE** [comment]
@WereCatf and @perexg:

Thanks...it's working! :+1:

@WereCatf 
Yes, the problem with simultaneously use of multiple tuners (Repeater DVB-C = 2; FRITZ!Box 6490 = 4) to 1 destination IP seems to be a general problem. Hope AVM will fix it in future firmware. For now I'll only enable 1 tuner.

**Comment by Stevo83** [comment]
The patch is working for me as well (using an AVM DVB-C repeater). I experienced two minor issues:
- When setting up, I selected pre-defined muxes for my region. Tvheadend started automatically scanning the muxes, but failed after scanning the first one. When I enabled them manually one after another, scans were successful.

- The second one might be related to the first: Just like StofLE channel switching (with the kodi frontend) does not work properly. I need to stop the running channel before tuning in to the next. 

Apart from this, setting up and using the device with tvheadend works beautiful. Thank you very much for your work!

**Pull request closed without merging**
