### PR TITLE
Migrate libavformat muxer to FFmpeg 5 API

### PR DESCRIPTION
**Pull request by chewi**
As you may be aware, Tvheadend does not build against FFmpeg 5 due to API changes involving codecpar and BSF. This is going to become a headache for distributions quite soon. I tried to update the code to make it work, but have struggled due to what seems to be a slightly complex use case. I'm submitting what I have so far so that no one has to start from scratch with this. The `/* Check */` comments show where the result should be checked.

There isn't much documentation around this API or how to migrate, but I did find [a great example](https://github.com/mgba-emu/mgba/blob/31201d49033a0519e3272e3359ca75b97c183e6d/src/feature/ffmpeg/ffmpeg-encoder.c) of code supporting both the old and new APIs. I don't think you need to support both, but it still demonstrates how you can migrate. Unfortunately, it's a simpler use case. Look for `FFMPEG_USE_CODECPAR` and `FFMPEG_USE_NEW_BSF`.

### CODE REVIEW

**Comment by Flole998** [comment]
As you can see your version does not build currently when using the static ffmpeg (which still uses ffmpeg 4.x). As there are only a few distributions currently providing ffmpeg 5 packages it's not acceptable to break it for all of them, so you should really use ffmpeg 4 for now.

**Comment by chewi** [comment]
It doesn't build because this work is incomplete, as I said. The new API is present in 4.x, possibly as far back as 4.0 from what I can see. The old API has been deprecated for a long time.

**Comment by chewi** [comment]
See [this commit](https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/39e9a7a80fd30d11f04031a141cf0db20be4953f?hp=dbfc31b86ec9a9f9609c72fc618f48238301cc6f) from 2017!

**Comment by woooow1** [comment]
@chewi, what exactly trying to change? Maybe this warning: libav: avformatcontext: using avstream.codec to pass codec parameters to muxers is deprecated, use avstream.codecpar instead??? Migration to new api need a lot of tvheadend code to be adapted. More trouble is libavresample, wich is also obsolete!

**Comment by chewi** [comment]
From [Gentoo bug #834399](https://bugs.gentoo.org/834399), trying to build against FFmpeg 5 looks like this:

```
src/muxer/muxer_libav.c:37:3: error: unknown type name ‘AVBitStreamFilterContext’
   37 |   AVBitStreamFilterContext *lm_h264_filter;
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
src/muxer/muxer_libav.c:38:3: error: unknown type name ‘AVBitStreamFilterContext’
   38 |   AVBitStreamFilterContext *lm_hevc_filter;
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
src/muxer/muxer_libav.c: In function ‘lav_muxer_add_stream’:
src/muxer/muxer_libav.c:81:3: error: unknown type name ‘AVCodecContext’; use ‘struct’ keyword to refer to the type
   81 |   AVCodecContext *c;
      |   ^~~~~~~~~~~~~~
      |   struct 
src/muxer/muxer_libav.c:88:9: error: ‘AVStream’ has no member named ‘codec’
   88 |   c = st->codec;
      |         ^~
src/muxer/muxer_libav.c:89:4: error: request for member ‘codec_id’ in something not a structure or union
   89 |   c->codec_id = streaming_component_type2codec_id(ssc->ssc_type);
      |    ^~
src/muxer/muxer_libav.c:100:6: error: request for member ‘rc_buffer_size’ in something not a structure or union
  100 |     c->rc_buffer_size = 224*1024*8;
      |      ^~
src/muxer/muxer_libav.c:123:8: error: request for member ‘extradata_size’ in something not a structure or union
  123 |       c->extradata_size = hdr.sb_ptr;
```

That bug report also showed the libavresample issue you mention, but that was against Tvheadend V4.2.8. Commit 014bb9505e1d7eb6e37e10931dd89ab3b1a0dc01 removed the only reference to avresample.h, but this change has never been released, despite being made way back in 2016. I believe the only remaining issue is in this muxer.

**Comment by pimzand** [comment]
Fedora 36 (with rpmfusion) comes with ffmpeg 5.
In Fedora 35, that came with ffmpeg 4, I could build tvheadend with ffmpeg dynamically.
I now had to switch to static build using the ffmpeg provided by tvheadend.

There may not be many other distributions using ffmpeg 5,
but at some point it would make sense for tvheadend to switch to ffmpeg 5,
and provide static build methods for distibutions that do not provide it.

**Comment by chewi** [comment]
Like I said, the new ABI will work with 4.x as the old ABI was already deprecated. This should have been done years ago.

**Comment by woooow1** [comment]
I can help only with ''FFMPEG_USE_CODECPAR''. With this code, warning is gone from log! I am not sure, that this is the right way to use, so any review and help is welcome!
[muxer_libav.zip](https://github.com/tvheadend/tvheadend/files/8868312/muxer_libav.zip)

**Comment by marillat** [comment]
@chewi Thanks for this PR but you have not seen build error with  src/input/mpegts/iptv/iptv_libav.c

```
CC              src/input/mpegts/iptv/iptv_libav.o
src/input/mpegts/iptv/iptv_libav.c: In function 'iptv_libav_thread':
src/input/mpegts/iptv/iptv_libav.c:118:57: error: 'AVStream' has no member named 'codec'
  118 |     out_stream = avformat_new_stream(la->octx, in_stream->codec->codec);
      |                                                         ^~
src/input/mpegts/iptv/iptv_libav.c:128:15: error: 'AVStream' has no member named 'codec'
  128 |     out_stream->codec->codec_tag = 0;
      |               ^~
src/input/mpegts/iptv/iptv_libav.c:130:17: error: 'AVStream' has no member named 'codec'
  130 |       out_stream->codec->flags |= AV_CODEC_FLAG_GLOBAL_HEADER;
      |                 ^~
src/input/mpegts/iptv/iptv_libav.c:130:35: error: 'AV_CODEC_FLAG_GLOBAL_HEADER' undeclared (first use in this function)
  130 |       out_stream->codec->flags |= AV_CODEC_FLAG_GLOBAL_HEADER;
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
src/input/mpegts/iptv/iptv_libav.c:130:35: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by Leatherface75** [comment]
Anything new? Would be nice to get rid of ffmpeg4.

**Comment by loznic89** [comment]
> As you may be aware, Tvheadend does not build against FFmpeg 5 due to API changes involving codecpar and BSF. This is going to become a headache for distributions quite soon. I tried to update the code to make it work, but have struggled due to what seems to be a slightly complex use case. I'm submitting what I have so far so that no one has to start from scratch with this. The `/* Check */` comments show where the result should be checked.
> 
> There isn't much documentation around this API or how to migrate, but I did find [a great example](https://github.com/mgba-emu/mgba/blob/31201d49033a0519e3272e3359ca75b97c183e6d/src/feature/ffmpeg/ffmpeg-encoder.c) of code supporting both the old and new APIs. I don't think you need to support both, but it still demonstrates how you can migrate. Unfortunately, it's a simpler use case. Look for `FFMPEG_USE_CODECPAR` and `FFMPEG_USE_NEW_BSF`.

you can try with this.

https://hub.docker.com/r/gee1/tvheadend

**Comment by woooow1** [comment]
@loznic89 Personally, I dont want to try unknown precompiled binaries! If I want, there is other closed source softwares...  Where is source code? If you want, and most important-if you know how to resolve this issue, feel free to support THIS progect!

**Comment by loznic89** [comment]
it was done by a user of a german satellite forum (linuxsat-support.com).

the code is on github (https://github.com/Gee1111)

**Comment by loznic89** [comment]
> @loznic89 Personally, I dont want to try unknown precompiled binaries! If I want, there is other closed source softwares... Where is source code? If you want, and most important-if you know how to resolve this issue, feel free to support THIS progect!

it was done by a user of a german satellite forum (linuxsat-support.com).

the code is on github (https://github.com/Gee1111)

**Comment by chewi** [comment]
Looking at their repository, they tried a few times to apply my half-finished changes, then eventually gave up and reverted them. :joy:

**Comment by Leatherface75** [comment]
> Looking at their repository, they tried a few times to apply my half-finished changes, then eventually gave up and reverted them. joy

When will you finish this?
FFmpeg 4.x is getting old now.

**Comment by chewi** [comment]
> When will you finish this? FFmpeg 4.x is getting old now.

If you're asking me, then look elsewhere. I haven't actually used Tvheadend for years, and even when I did, I didn't use it with FFmpeg. I only submitted this because I'm still the Gentoo package maintainer and because I wanted to be helpful. Unfortunately, it required more knowledge and effort than I was able to put in.

**Comment by uknunknown** [comment]
@Flole998 I think we need to split this task in multiple phases; I made the first step: update from 'codec' to 'codecpar'.
https://github.com/uknunknown/tvheadend
Now I am not receiving the deprecation warning when I use libav.
I was able to test only vaapi (Intel) and software encoding; we still need some testers for raspberry and nvenc.
My code is enabled with a define so you can easily go back and forth to test with and without my changes.
`#define USE_FFMPEG_CODECPAR 1`
Note: some of libav stream profiles (for example - WEBTV profile H264/vorbis/MP4 - that comes preloaded) are not working (in my case) before or after the change.
Is important to be able to go back and forth easily in order to check if both combinations are failing.

How do you propose to continue? should I submit the PR and we wait for people to report ... or we wait for people to report here?

**Comment by Saentist** [comment]
> @Flole998 I think we need to split this task in multiple phases; I made the first step: update from 'codec' to 'codecpar'. https://github.com/uknunknown/tvheadend Now I am not receiving the deprecation warning when I use libav. I was able to test only vaapi (Intel) and software encoding; we still need some testers for raspberry and nvenc. My code is enabled with a define so you can easily go back and forth to test with and without my changes. `#define USE_FFMPEG_CODECPAR 1` Note: some of libav stream profiles (for example - WEBTV profile H264/vorbis/MP4 - that comes preloaded) are not working (in my case) before or after the change. Is important to be able to go back and forth easily in order to check if both combinations are failing.
> 
> How do you propose to continue? should I submit the PR and we wait for people to report ... or we wait for people to report here?

There is more simple variant, current unstable stay stable and PR go to main.

**Comment by Flole998** [comment]
There won't be stable builds anymore, just not feasible with no maintainers and to ask people submitting PRs to backport them won't happen.

**Comment by uknunknown** [comment]
@Flole998 so you are saying 4.4 will never be release (to be integrated in OSs)? How is the procedure to 'release a new version'? In my naive understanding, I was thinking that after we have a 'gap' in submission with not issues reported you release a new stable version.

**Comment by Flole998** [comment]
The new CI system and the new repo isn't set up for stable/unstable releases at all. There is no stable and unstable anymore, there is simply only Tvheadend now, a single version.

**Comment by Saentist** [comment]
> The new CI system and the new repo isn't set up for stable/unstable releases at all. There is no stable and unstable anymore, there is simply only Tvheadend now, a single version.

That's why all make `Releases`
Even automatically.

**Comment by Flole998** [comment]
Automatic releases? How should some automatic system know when it's a good time to make a release. Anyways, there is NOTHING set up for that, so automatic releases won't happen.

**Comment by Saentist** [comment]
> Automatic releases? How should some automatic system know when it's a good time to make a release. Anyways, there is NOTHING set up for that, so automatic releases won't happen.

What is a problem `once a month` or `on each 50 commits`?

**Comment by Flole998** [comment]
Uhmm, maybe that there is nobody who does it?

What's the point in doing that? Just use latest master...

**Comment by Saentist** [comment]
> Uhmm, maybe that there is nobody who does it?
> 
> What's the point in doing that? Just use latest master...

How many can build it alone?
5-10% more or less?
Most of people search for prebuild packages, 
no matter that is cut of features.

**Comment by Flole998** [comment]
And that's why there is a repository that contains the latest build. But this is offtopic here.

**Comment by mralapete** [comment]
Simple copy/paste build instructions can be found on the TVH forum. If anyone is fearful of using them there’s a number of PPA’s that can be added to your system and TVH can be installed from there. The least amount of work for maintainers on the administration front the better. Things are fine the way they are. Why change them.

**Comment by Flole998** [comment]
The official repository provides builds for over 40!!! different linux versions, that should be more than enough.

**Comment by Saentist** [comment]
> The official repository provides builds for over 40!!! different linux versions (different archs and version combos), that should be more than enough.

Just Debian derivate's not different distribution's 

[RPM](https://github.com/marketplace/actions/build-rpm-action), [APK](https://github.com/marketplace/actions/alpine-build-apk), [OPKG](https://github.com/marketplace/actions/openwrt-imagebuilder-github-action) etc missing.

**Comment by Flole998** [comment]
> > The official repository provides builds for over 40!!! different linux versions (different archs and version combos), that should be more than enough.
> 
> Just Debian derivate's not different distribution's
> 
> [RPM](https://github.com/marketplace/actions/build-rpm-action), [APK](https://github.com/marketplace/actions/alpine-build-apk), [OPKG](https://github.com/marketplace/actions/openwrt-imagebuilder-github-action) etc missing.

Pull requests are welcome.

But again: Offtopic! Back to topic!

**Comment by uknunknown** [comment]
Phase 2 (towards ffmpeg5) we need to remove "AVBitStreamFilterContext" ... for that I have a proposal:
https://github.com/uknunknown/tvheadend
Some of the containers combination are not working (even before my changes) so I decided to add a define that allows the tested to move back and forth easily (comment line 35 "#define USE_BSF" from src/muxer/muxer_libav.c ).
I performed tests with VAAPI + AAC on AMD64 with Ubuntu 22.04 --> I would appreciate if some brave testers will test other configuration (especially software encoding, RaspberryPI and nvenc). Please post good or bad results in this thread.

**Comment by th0ma7** [comment]
> I would appreciate if some brave testers will test other configuration (especially software encoding, RaspberryPI and nvenc). Please post good or bad results in this thread.

If that can help I may be able to provide experimental packages for Synology NAS https://synocommunity.com/package/tvheadend.  I need first to publish updated `ffmpeg` packages https://github.com/SynoCommunity/spksrc/pull/5620 then I could manage something out if that can help?  vaapi is enabled for x86_64 using either older/newer driver version depending of the cpu type.

Although I have really limited cycles over the coming two weeks and this will take me a bit of time to get this done...

**Comment by uknunknown** [comment]
th0ma7, any help on testing is welcome. 

Flole998, I also summited a PR (https://github.com/tvheadend/tvheadend/pull/1512) - after I cleaned up the 'define' - to verify if we have any failures during your checks. Please let me know if you see any source code issues that must be addressed.

**Comment by uknunknown** [comment]
Phase 3 (this is part of phase 1 migrate to codecpar): I found 'codec' being used also in other parts of source code. We need to migrate those sections to 'codecpar'
https://github.com/uknunknown/tvheadend/tree/test_iptv_libav
The good news is that I changed the source code and is compiling; the bad news is that I don't know how to exercise this part of code. Based on location: /src/input/mpegts/iptv/iptv_libav.c my guess is we need a: Source IPTV in a MPEGTS container. Frankly I got stuck at this point :( ... without external help I cannot move forwards (because I don't have such a source for my tests).
HELP!

**Comment by uknunknown** [comment]
after implementing https://github.com/tvheadend/tvheadend/pull/1514
the branch: https://github.com/uknunknown/tvheadend/tree/test_ffmpeg5
is compiling with ffmpeg 5.1.2.
I don't thing is the most optimal implementation ... but is a starting point.
I hope someone will takeover from here and polish the code.
I only tested with Intel amd64 (ubuntu 20.05 and 22.04), probably is wise to test also other platforms.

**Comment by Leatherface75** [comment]
> 

Compiled and running here now.
Seems to work but haven't tried things like recording,transcoding etc yet.

**Comment by uknunknown** [comment]
for early adopters I have a branch with ffmpeg6 (6.0).
https://github.com/uknunknown/tvheadend/tree/test_ffmpeg6

**Comment by Leatherface75** [comment]
> 

Hmms i am getting this with ffmpeg6

```
/usr/lib64/gcc/x86_64-suse-linux/13/../../../../x86_64-suse-linux/bin/ld: /usr/src/packages/BUILD/tvheadend-4.3.git20230327/build.linux/src/transcoding/transcode/video.o: in function `tvh_video_context_encode':
/usr/src/packages/BUILD/tvheadend-4.3.git20230327/src/transcoding/transcode/video.c:313: undefined reference to `av_frame_get_best_effort_timestamp'
collect2: error: ld returned 1 exit status
make: *** [Makefile:715: /usr/src/packages/BUILD/tvheadend-4.3.git20230327/build.linux/tvheadend] Error 1
fel: Dålig slutstatus från /var/tmp/rpm-tmp.SFbTAq (%build)

RPM build errors:
    Dålig slutstatus från /var/tmp/rpm-tmp.SFbTAq (%build)
```

**Comment by Leatherface75** [comment]
> for early adopters I have a branch with ffmpeg6 (6.0). https://github.com/uknunknown/tvheadend/tree/test_ffmpeg6

That's even better.
I am testing it right now and seems to work what i can see.

**Comment by uknunknown** [comment]
@Flole998 we got to the point where we have to step to ffmpeg5.
https://github.com/uknunknown/tvheadend/tree/dev_ffmpeg5
Please take a look at my initial proposal and let me know your opinion.
Highlights:
1. I added a config 'ffmpeg5' that will allow to move easy back and forth. Take into account soon after I plan to update to ffmpeg6. I will add another config at that point (probably 'ffmpeg6').
2. this switch is only selecting that ffmpeg to download and compile ... all other code changes are dependent on LIBAVCODEC_VERSION_MAJOR (I think is better on long run)
3. The only questionable decision is: should we set this config to on (in order to force compilation with ffmpeg5 for all users)? 
Let me know what do you recommend.

**Comment by Flole998** [comment]
If we compile with static ffmpeg we could use the latest version, it doesn't really matter. If we link against a user-provided ffmpeg we basically need to handle all kinds of versions.

**Pull request closed without merging**
