### PR TITLE
Makefile.ffmpeg nvenc update

### PR DESCRIPTION
**Pull request by Saentist**
FFNVCODEC_VER  = 11.1.5.0 -> 12.1.14.0

### CODE REVIEW

**Comment by CvH** [comment]
just saying, that breaks the NV usage at old outdated EOL distros that are activly supported (for whatever reasons) by Tvh
from a quick look just Ubuntu 20.04 supports the >=530 driver

11.1.5.0
> Minimum required driver versions:
> Linux: 470.57.02 or newer

12.1.14.0
> Minimum required driver versions:
> Linux: 530.41.03 or newer

**Comment by Saentist** [comment]
FFMpeg greater then 4 broke already lot of old OS's

Maby some IF>THEN>ELSE strategy in building scenarios needed.
Linear building is not best solution for all OS's and Architectures.

**Comment by CvH** [comment]
> Maby some IF>THEN>ELSE strategy in building scenarios needed.

or in general just drop support for EOL distros
no idea if there is a reasonable demand from Ubuntu 14/16/18.04 users that need beleeding edge Tvh builds and are not able to build their own

**Comment by Flole998** [comment]
Old distros are provided mainly for repurposing old devices that can't really be upgraded (like NAS systems, routers, receivers and whatnot), if nvenc breaks for those it's not a big deal.

**Comment by Saentist** [comment]
> > Maby some IF>THEN>ELSE strategy in building scenarios needed.
> 
> or in general just drop support for EOL distros no idea if there is a reasonable demand from Ubuntu 14/16/18.04 users that need beleeding edge Tvh builds and are not able to build their own

I personally use 14 and 16 just because newer OS kernel (4.4+) do not support driver building drivers for some tuners

**Comment by Flole998** [comment]
Please fix the failing builds.

**Pull request merged**
