### PR TITLE
Add XDG support

### PR DESCRIPTION
**Pull request by oliv3r**
This series adds support for the [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

### CODE REVIEW

**Comment by oliv3r** [comment]
Sorry, I hadn't, with codeball always failing, it's hard to miss (I was hoping we could fix codeball with the installation, I'll look at it again, but unfamiliar with codeball itself).

But, lets fix it :)

**Comment by oliv3r** [comment]
> I think codeball might be broken

yeah, probably.

Anyway, I couldn't reproduce it with the :latest variant (of both alpine or ubuntu), but on my local arch compiler it did barf, it's a new (good) feature of gcc! I'm supprised it's not triggering on other locations, but regardless, it's fixed.

**Comment by oliv3r** [comment]
> Now it's failing with a different error, it's missing 1 byte for the null-Termination apparently.

Yeah i saw; if these API's where just a bit more consistent with eachother, anyway, lets see what happens in the next 15 minutes :p

**Comment by oliv3r** [comment]
So I found why I can't reproduce it, my Makefile doesn't contain ` -Wstringop-truncation`, I don't find it with git-grep either, so somewhere something is addiding this flag (something like `-Wall`? I haven't looked into detail. But these hidden/explicit things are not that great.

Personally, I"m a huge proponent to catch as much as we can with these kind of build flags. Where can I find these definitions, and can we not just add them to the main Makefile?

**Comment by Flole998** [comment]
There's `-werror` somewhere and there's a configure option `--nowerror` or something like that, maybe that points in the right direction? I remember that it was turned off for some builds to allow them to compile, especially since it got added to ffmpeg aswell and broke compilation there when using the static ffmpeg option.

**Comment by oliv3r** [comment]
Success; I"ll test it a little bit more with the fix, but gotta fix my containers a little bit first ;) But a review would be welcome in the meantime.

**Comment by Flole998** [comment]
Looks good to me, is it ready for merging?

**Comment by oliv3r** [comment]
@Flole998 yep, I've tried a few scenario's and they all seem to use the correct path. So lets merge it :)

**Comment by oliv3r** [comment]
@Flole998 ah shit sorry, I forgot to push my very last, which means I committed some white-space snafu and forgot a commit. I'll open a new MR to fix those. This MR isn't broken or anything though.

**Comment by Flole998** [comment]
Could this be the cause of https://tvheadend.org/issues/6296?

**Comment by oliv3r** [comment]
@Flole998 I would not be supprised, let me try and reproduce it, I hadn't used `-f` during my testing

**Pull request merged**
