### PR TITLE
HTSP: Added the "comment" and "episode" fields.

### PR DESCRIPTION
**Pull request by agitate**
I've added in the comment and episode fields to the dvr entries in HTSP responses.

### CODE REVIEW

**Comment by perexg** [comment]
Merged. Thanks.

**Comment by Hedda** [comment]
Does it already have a "season" field? (also, was this PR merged? GitHub sais it was closed)

**Comment by agitate** [comment]
No, but the season information is included in the episode field. Note that the format of the episode field stored in the dvrentry (which is a full text description, such as, "Season 2, Episode 3") does not match that returned in an event (which would be 2.3). Neither of these match the 0 based numbering found in the XMLTV format. It would be nice to consolidate them (and I'll probably look in to that next).

This change was indeed merged (commit ae8565a02f3857f0201ed0d78bce2ebe2d3a1ae1).

**Comment by agitate** [comment]
Sorry, minor correction: dvrentries store it like this "Season 2.Episode 3" (with a dot between as opposed to a comma and a space).

**Pull request closed without merging**
