### PR TITLE
NetCeiver support

### PR DESCRIPTION
**Pull request by walinsky**
Hi,

this adds NetCeiver support.
Sven Wegener wrote this software ( https://github.com/swegener/tvheadend/tree/netceiver-support ), and I've been using it without any problems for 5 years now.
I think it's about time to add this to the main source tree. There's thousands of users of Reelbox Avantgarde and NetCeiver who could benefit from this patch.
I've updated the code so it can be merged in the master branch.

Please let me know what you think.

### CODE REVIEW

**Comment by Saentist** [comment]
> I’m using TVH for many years and have never come across Netceiver. I just did a quick search on the topic and everything appears to be in the German language. Are you sure there are thousands using it.

Same number of users with use hdhomerun, there's no problem to exist.

**Comment by Flole998** [comment]
> Same number of users with use hdhomerun, there's no problem to exist.

Except that it bloats up the codebase even more

**Comment by Saentist** [comment]
> > Same number of users with use hdhomerun, there's no problem to exist.
> 
> Except that it bloats up the codebase even more

Offer better code :stuck_out_tongue_winking_eye: and post PR
or merge this.

**Comment by Flole998** [comment]
Or reject this to prevent the codebase from being bloated up. Those are the options available to me, and I am not sure yet which one I'll choose.

**Comment by mralapete** [comment]
That’s why I never heard of it. I don’t use HD Homerun. Definitely don’t need any further bloat.

**Comment by Flole998** [comment]
This would add more unmaintained code that I can't test nor maintain due to lack of hardware and lack of time, so at this point this can't be merged. You can use the pipe input option to connect to hardware that Tvheadend doesn't natively support.

**Pull request closed without merging**
