### PR TITLE
Add fedora 34 / update rpm spec

### PR DESCRIPTION
**Pull request by mpmc**
I've tried my best to get Python3 / Python2 to play nice with new/old versions of Fedora here.

NOTE: the build fails due to ffmpeg, that may need an update?

### CODE REVIEW

**Comment by Flole998** [comment]
Maybe you need to add `--nowerror` to get the fffmpeg build to go through? Same for CentOS but no clue how that needs to be done there, I've done it for some of the builds that require it.

**Comment by mpmc** [comment]
Feel free to have a look yourself if you get chance :)

**Comment by Flole998** [comment]
python2 is wanted during build but is not available, that's the issue. You probably want to add `--python=python3` to the configure call.

**Comment by Flole998** [comment]
@mpmc Have you tried my suggestion?

**Comment by mpmc** [comment]
I haven't sorry, things have been hectic atm. If you want you can steal this PR with your suggestions added :)

**Comment by ekuester** [comment]
Stumbled accidently over this discussion. Perhaps you will try my attached .spec file to build a .rpm for Fedora 34. To fetch the related .tar.gz file use `wget https://github.com/tvheadend/tvheadend/archive/637844055c186e981495da711e4887806f656c98/tvheadend-637844055.tar.gz` ...
[tvheadend.spec.txt](https://github.com/tvheadend/tvheadend/files/7254965/tvheadend.spec.txt)

**Pull request closed without merging**
