### PR TITLE
Use a build matrix in GitHub Actions to build on more platforms

### PR DESCRIPTION
**Pull request by Jalle19**

### CODE REVIEW

**Comment by Flole998** [comment]
I'm sorry but this can't be merged at the moment as there's a major rebuild of the entire build stuff going on at my fork. All that's left is fixing a few failing builds there by installing a more recent python version so the build can be uploaded to the new repository.

**Comment by Jalle19** [comment]
I see, didn't know you were working on this already. I was mainly looking to fix the build on Debian 11 and figured it'd make sense to make a better CI pipeline while I'm at it.

Do you want any help with the workflow on your fork?

**Comment by Flole998** [comment]
Sure, actually I think I can already merge it at this point and then the remaining builds can be fixed. Some targets need newer python versions, so downloading and compiling a new-ish python version is what's missing there. Other than that it's pretty much complete.

**Comment by Flole998** [comment]
Actually we can still

**Comment by Flole998** [comment]
Actually this can still be used as CI target so all PRs are checked with this. So if you want to resolve the merge conflict we can get this in aswell.

**Comment by Jalle19** [comment]
Okay, so you're looking to have separate jobs for pull requests only?

**Comment by Flole998** [comment]
I've merged my changes and there are now 3 jobs:
1. Coverity scan job (this one needs to be modified to include as many features as possible)
2. CI job (this one runs on all PRs, here your changes can be added)
3. Repo build job (that's the python issue I mentioned earlier)

**Pull request closed without merging**
