### PR TITLE
Adding CORS headers

### PR DESCRIPTION
**Pull request by shukydvir**
Hi,

This implements 

https://tvheadend.org/issues/852

I'm currently building a web UI and I want it to be static HTML no server side code.

Thanks

### CODE REVIEW

**Comment by perexg** [comment]
I don't like it. The allowed IPs / hostnames should be configurable.

**Comment by Jalle19** [comment]
I don't see the problem with this, these headers are only used by browsers.

**Comment by Jalle19** [comment]
Any news on this? Now that there's been more work on unifying the API there are probably people interested in creating third-party web interfaces for tvheadend. CORS is a hard requirement if that's going to be possible.

@perexg http://enable-cors.org/ has more information

**Comment by perexg** [comment]
I'm busy with the API rewrite for configuration tabs at the moment, but the goal of all of these rewrites is to allow to add new various configuration switches to the configuration tabs in an easy way. So, hold on.

**Comment by perexg** [comment]
Merged and added: 198ecc37f7ef8b5af75f82ef8035d49ee8996fbc

**Pull request closed without merging**
