### PR TITLE
WebUI: Fix some tooltips

### PR DESCRIPTION
**Pull request by Trujulu**
Note: " is not shown while ' yes. Some text was truncated, so I replaced it.

image

### CODE REVIEW

**Comment by Flole998** [comment]
I dont think we shold have a period after single words like "Play" or "Fullscreen", it looks completely odd to have a "Fullscreen." tooltip.

**Comment by Trujulu** [comment]
> I dont think we shold have a period after single words like "Play" or "Fullscreen", it looks completely odd to have a "Fullscreen." tooltip.

Yes, it would be better to delete those tooltips.

**Comment by ljalves** [comment]
This seems more like personal preferences but honestly I don't get why the replacement of the " with ' ?
In my opinion, the correct symbol to quote words one should be " and the ' should be used on words like "don't" or "wouldn't".

I also don't like the dots in the end :)

**Comment by Trujulu** [comment]
I will check it when I have time

**Pull request closed without merging**
