### PR TITLE
SAT>IP Server Implementation

### PR DESCRIPTION
**Pull request by perexg**
This request gathers code for the SAT>IP Server implementation.

The implementation is almost complete and tested now except the PSI table rewrite routines (filtering, CA).

Implemented things:

- UPnP announce and discovery
- WEBUI Configuration (tuners, network assignment)
- RTSP server
- RTP/RTCP senders
- correct PID filtering
- implement a way to forward descrambled PIDs
- partly tested with the Elgato SAT>IP Android application

Remaining things:

- PSI table parser and encoder (to remove CA info, filtered PIDs)
- rest... mainly debugging...

Notes:

The configuration is in the global config (number of tuners) and in the network settings (the source selection which is the integer identification of "position" for DVB-S (use 1 if you have only one DVB-S network), for DVB-T/C this value must be 1 to activate the SAT>IP Server for the given network).

TVH Server / Client uses own mechanism to pass the custom RTSP port (9983). The extra HTTP header is used when the XML description file is served "X-SATIP-RTSP-Port". Note that SAT>IP specification allow only standard RTSP port 554, so tvh must be run with root priviledges to bind to this port (the root priviledges are not used for standard operation when -u parameter is used - only for this initialization like other servers like apache or so do..). The maximum number for the sources (positions) is passed using "X-SATIP-Sources" header.

The internal MPEG-TS PID handling was updated to allow custom filtering for the SAT>IP server subscriptions, but the HTTP streaming benefits from this change too, because the mux play URL (http://host:9981/play/stream/mux/ or http://localhost:9981/stream/mux/) allow to pass the list of subscribed PIDs with the pids= argument now.

BTW: Hardware donations (SAT>IP clients) for testing will be appreciated. (Call to the hardware vendors.)

Last modification: 2015/Mar/17 16:53 CET

### CODE REVIEW

**Comment by ckarrie** [comment]
When can we start testing?

Btw: Shouldn't it be possible to use another tvh instance as sat>ip client?

**Comment by 9000h** [comment]
@perexg 
nice to see what progress you make, but I may not understand up to now what's needed to get you code running as expected, when I try a rtsp request I only get a 400 reply in the debug.

**Comment by perexg** [comment]
@9000h : Configure network with the SAT>IP Source 1, assign it to a tuner. Then enable SAT>IP Server (RTSP port, tuner type) in the global config and it should work.

**Comment by 9000h** [comment]
that was what I did, hmm

**Comment by perexg** [comment]
What's your client? Could you show me the network dump for the RTSP communication (using wireshark or tcpdump) ?

**Comment by 9000h** [comment]
I did try with vlc, thats probably the issue.

**Comment by 9000h** [comment]
2015-03-18 13:40:23.004 [   INFO] subscription: 002B: "epggrab" subscribing on "none", weight: 4, adapter: "DRXK DVB-C DVB-T : DVB-C #0", network: "KDG", mux: "642MHz", provider: "<N/A>", service: "Raw PID Subscription"
2015-03-18 13:40:23.005 [  DEBUG] mpegts: 426MHz in KDG - add raw service
2015-03-18 13:40:23.005 [  DEBUG] service: 426MHz in KDG si 0xaac7af38 DRXK DVB-C DVB-T : DVB-C #0 weight 4 prio 0 error 0
2015-03-18 13:40:23.764 [  DEBUG] linuxdvb: DRXK DVB-C DVB-T : DVB-C #0 - status    GOOD (SIGNAL | CARRIER | VITERBI | SYNC | SIGNAL)
2015-03-18 13:40:23.764 [  DEBUG] linuxdvb: DRXK DVB-C DVB-T : DVB-C #0 - locked
2015-03-18 13:40:23.765 [  DEBUG] mpegts: 642MHz in KDG - open PID 0000 (0) [20/0xaae816a8]
2015-03-18 13:40:23.767 [  DEBUG] mpegts: 642MHz in KDG - open PID 0001 (1) [16/0xaa9d5500]
2015-03-18 13:40:23.767 [  DEBUG] mpegts: 642MHz in KDG - open PID 0010 (16) [16/0xaab074f0]
2015-03-18 13:40:23.767 [  DEBUG] mpegts: 642MHz in KDG - open PID 0011 (17) [20/0xaefe8e60]
2015-03-18 13:40:23.767 [  DEBUG] mpegts: 642MHz in KDG - open PID 0011 (17) [16/0xaac49958]
2015-03-18 13:40:28.000 [  DEBUG] service: 642MHz in KDG: Status changed to [Graceperiod expired] [Data timeout]
2015-03-18 13:40:33.022 [  ERROR] http: 192.168.178.133: rtsp://192.168.178.126/?freq=338.000&msys=dvbc&sr=6900&mtype=256qam&pids=0,100,101,104,102,103,106 -- 400
2015-03-18 13:40:33.024 [  ERROR] http: 192.168.178.133: rtsp://192.168.178.126/?freq=338.000&msys=dvbc&sr=6900&mtype=256qam&pids=0,100,101,104,102,103,106 -- 400
2015-03-18 13:40:38.035 [  ERROR] http: 192.168.178.133: rtsp://192.168.178.126:554 -- 400

**Comment by perexg** [comment]
VLC does not support SAT>IP as far as I know: https://trac.videolan.org/vlc/ticket/11929 . SAT>IP RTSP usage is very limited and tvheadend supports only necessary parts, because HTTP streaming is better for most purposes.

**Comment by 9000h** [comment]
you are right, but all servers out there support vlc (Telestar Digibit R1, Octonet, Dvbviewer RS, minisatip, satpi)

**Comment by perexg** [comment]
@9000h : OK, I added support for standard RTSP, too. It might be useful for some debugging purposes.

**Comment by 9000h** [comment]
I still missing something or have my setup not right
```
root@bananas:/usr/src/satip/tvheadend# ./build.linux/tvheadend --noacl --trace satips
2015-03-19 12:36:59.138 [   INFO] main: Log started
2015-03-19 12:36:59.153 [   INFO] satips: SAT>IP Server initialized (HTTP 192.168.178.126:9981, RTSP 192.168.178.126:554, descramble 1, muxcnf 0)
2015-03-19 12:36:59.153 [   INFO] satips: SAT>IP Server tuners: DVB-T/T2 0/0, DVB-S/S2 0/0, DVB-C/C2 1/0, ATSC 0, DVB-Cable/AnnexB 0
2015-03-19 12:36:59.170 [   INFO] config: loaded
2015-03-19 12:37:00.090 [   INFO] scanfile: DVB-T - loaded 43 regions with 729 networks
2015-03-19 12:37:00.090 [   INFO] scanfile: DVB-S - loaded 1 regions with 93 networks
2015-03-19 12:37:00.090 [   INFO] scanfile: DVB-C - loaded 16 regions with 51 networks
2015-03-19 12:37:00.090 [   INFO] scanfile: ATSC - loaded 2 regions with 14 networks
2015-03-19 12:37:01.692 [   INFO] linuxdvb: adapter added /dev/dvb/adapter0
2015-03-19 12:37:01.978 [   INFO] dvr: Creating new configuration ''
2015-03-19 12:37:01.978 [WARNING] dvr: Output directory for video recording is not yet configured for DVR configuration "". Defaulting to to "/root". This can be changed from the web user interface.
2015-03-19 12:37:01.978 [WARNING] access: Access control checking disabled
2015-03-19 12:37:01.979 [   INFO] CSA: Using 32bit parallel descrambling
2015-03-19 12:37:01.979 [   INFO] epggrab: module eit created
2015-03-19 12:37:01.979 [   INFO] epggrab: module uk_freesat created
2015-03-19 12:37:01.979 [   INFO] epggrab: module uk_freeview created
2015-03-19 12:37:01.980 [   INFO] epggrab: module viasat_baltic created
2015-03-19 12:37:01.999 [   INFO] epggrab: module opentv-ausat created
2015-03-19 12:37:02.000 [   INFO] epggrab: module opentv-skyuk created
2015-03-19 12:37:02.001 [   INFO] epggrab: module opentv-skyit created
2015-03-19 12:37:02.012 [   INFO] epggrab: module pyepg created
2015-03-19 12:37:02.012 [   INFO] epggrab: module xmltv created
2015-03-19 12:37:03.766 [   INFO] epgdb: loaded v2
2015-03-19 12:37:03.766 [   INFO] epgdb:   config     1
2015-03-19 12:37:03.766 [   INFO] epgdb:   channels   0
2015-03-19 12:37:03.766 [   INFO] epgdb:   brands     0
2015-03-19 12:37:03.766 [   INFO] epgdb:   seasons    0
2015-03-19 12:37:03.766 [   INFO] epgdb:   episodes   16758
2015-03-19 12:37:03.766 [   INFO] epgdb:   broadcasts 16758
2015-03-19 12:37:03.797 [ NOTICE] START: HTS Tvheadend version -unknown started, running as PID:7877 UID:0 GID:0, CWD:/usr/src/satip/tvheadend CNF:/root/.hts/tvheadend
2015-03-19 12:37:03.804 [   INFO] mpegts: 378MHz in KDG - tuning on DRXK DVB-C DVB-T : DVB-C #0
2015-03-19 12:37:03.805 [   INFO] subscription: 0001: "epggrab" subscribing on "none", weight: 4, adapter: "DRXK DVB-C DVB-T : DVB-C #0", network: "KDG", mux: "378MHz", provider: "<N/A>", service: "Raw PID Subscription"
2015-03-19 12:37:04.580 [   INFO] AVAHI: Service 'Tvheadend' successfully established.
2015-03-19 12:37:15.214 [WARNING] linuxdvb: DRXK DVB-C DVB-T : DVB-C #0 - read() EOVERFLOW
2015-03-19 12:37:25.734 [WARNING] linuxdvb: DRXK DVB-C DVB-T : DVB-C #0 - read() EOVERFLOW
2015-03-19 12:37:28.285 [  ERROR] http: 192.168.178.133: RTSP/1.0 DESCRIBE rtsp://192.168.178.126/?freq=338.000&msys=dvbc&sr=6900&mtype=256qam&pids=0,100,101,104,102,103,106 -- 400
2015-03-19 12:37:36.228 [WARNING] linuxdvb: DRXK DVB-C DVB-T : DVB-C #0 - read() EOVERFLOW
2015-03-19 12:37:38.000 [   INFO] subscription: 0001: "epggrab" unsubscribing
2015-03-19 12:37:39.000 [   INFO] mpegts: 121MHz in KDG - tuning on DRXK DVB-C DVB-T : DVB-C #0
2015-03-19 12:37:39.001 [   INFO] subscription: 0003: "epggrab" subscribing on "none", weight: 4, adapter: "DRXK DVB-C DVB-T : DVB-C #0", network: "KDG", mux: "121MHz", provider: "<N/A>", service: "Raw PID Subscription"
```

**Comment by perexg** [comment]
Could you retry ? But EOVERFLOW errors are more serious. Users report them for this branch, trying to analyze, where's the cause. Unfortunately, my DVB-T tuner works ok.

**Comment by 9000h** [comment]
looks bit better now but still no stream
```
./build.linux/tvheadend --noacl --trace satips
2015-03-19 13:15:50.292 [   INFO] main: Log started
2015-03-19 13:15:50.307 [   INFO] satips: SAT>IP Server initialized (HTTP 192.168.178.126:9981, RTSP 192.168.178.126:554, descramble 1, muxcnf 0)
2015-03-19 13:15:50.307 [   INFO] satips: SAT>IP Server tuners: DVB-T/T2 0/0, DVB-S/S2 0/0, DVB-C/C2 1/0, ATSC 0, DVB-Cable/AnnexB 0
2015-03-19 13:15:50.323 [   INFO] config: loaded
2015-03-19 13:15:51.239 [   INFO] scanfile: DVB-T - loaded 43 regions with 729 networks
2015-03-19 13:15:51.239 [   INFO] scanfile: DVB-S - loaded 1 regions with 93 networks
2015-03-19 13:15:51.239 [   INFO] scanfile: DVB-C - loaded 16 regions with 51 networks
2015-03-19 13:15:51.239 [   INFO] scanfile: ATSC - loaded 2 regions with 14 networks
2015-03-19 13:15:52.842 [   INFO] linuxdvb: adapter added /dev/dvb/adapter0
2015-03-19 13:15:53.136 [   INFO] dvr: Creating new configuration ''
2015-03-19 13:15:53.136 [WARNING] dvr: Output directory for video recording is not yet configured for DVR configuration "". Defaulting to to "/root". This can be changed from the web user interface.
2015-03-19 13:15:53.136 [WARNING] access: Access control checking disabled
2015-03-19 13:15:53.138 [   INFO] CSA: Using 32bit parallel descrambling
2015-03-19 13:15:53.138 [   INFO] epggrab: module eit created
2015-03-19 13:15:53.138 [   INFO] epggrab: module uk_freesat created
2015-03-19 13:15:53.138 [   INFO] epggrab: module uk_freeview created
2015-03-19 13:15:53.138 [   INFO] epggrab: module viasat_baltic created
2015-03-19 13:15:53.155 [   INFO] epggrab: module opentv-ausat created
2015-03-19 13:15:53.156 [   INFO] epggrab: module opentv-skyuk created
2015-03-19 13:15:53.157 [   INFO] epggrab: module opentv-skyit created
2015-03-19 13:15:53.167 [   INFO] epggrab: module pyepg created
2015-03-19 13:15:53.168 [   INFO] epggrab: module xmltv created
2015-03-19 13:15:54.839 [   INFO] epgdb: loaded v2
2015-03-19 13:15:54.839 [   INFO] epgdb:   config     1
2015-03-19 13:15:54.839 [   INFO] epgdb:   channels   0
2015-03-19 13:15:54.839 [   INFO] epgdb:   brands     0
2015-03-19 13:15:54.839 [   INFO] epgdb:   seasons    0
2015-03-19 13:15:54.839 [   INFO] epgdb:   episodes   16542
2015-03-19 13:15:54.839 [   INFO] epgdb:   broadcasts 16542
2015-03-19 13:15:54.870 [ NOTICE] START: HTS Tvheadend version -unknown started, running as PID:8259 UID:0 GID:0, CWD:/usr/src/satip/tvheadend CNF:/root/.hts/tvheadend
2015-03-19 13:15:54.877 [   INFO] mpegts: 378MHz in KDG - tuning on DRXK DVB-C DVB-T : DVB-C #0
2015-03-19 13:15:54.879 [   INFO] subscription: 0001: "epggrab" subscribing on "none", weight: 4, adapter: "DRXK DVB-C DVB-T : DVB-C #0", network: "KDG", mux: "378MHz", provider: "<N/A>", service: "Raw PID Subscription"
2015-03-19 13:15:55.624 [   INFO] AVAHI: Service 'Tvheadend' successfully established.
2015-03-19 13:16:06.284 [WARNING] linuxdvb: DRXK DVB-C DVB-T : DVB-C #0 - read() EOVERFLOW
2015-03-19 13:16:11.611 [WARNING] satips: 0/293144BD/1: create mux DVBC/ANNEX_A freq 338000000 sym 6900000 mod QAM/256 fec NONE
2015-03-19 13:16:11.614 [   INFO] mpegts: 338MHz in KDG - tuning on DRXK DVB-C DVB-T : DVB-C #0
2015-03-19 13:16:11.618 [   INFO] opentv-skyit: registering mux 338MHz in KDG
2015-03-19 13:16:11.625 [   INFO] subscription: 0003: "SAT>IP" subscribing on "none", weight: 100, adapter: "DRXK DVB-C DVB-T : DVB-C #0", network: "KDG", mux: "338MHz", provider: "<N/A>", service: "Raw PID Subscription", hostname="192.168.178.133", username="<N/A>", client="LibVLC/2.0.8 (LIVE555 Streaming Media v2011.12.23)"
2015-03-19 13:16:16.000 [   INFO] mpegts: 338MHz in KDG - scan no data, failed
2015-03-19 13:16:16.421 [WARNING] linuxdvb: DRXK DVB-C DVB-T : DVB-C #0 - read() EOVERFLOW
2015-03-19 13:16:19.004 [   INFO] mpegts: 378MHz in KDG - tuning on DRXK DVB-C DVB-T : DVB-C #0
2015-03-19 13:16:19.005 [   INFO] subscription: 0005: "epggrab" subscribing on "none", weight: 4, adapter: "DRXK DVB-C DVB-T : DVB-C #0", network: "KDG", mux: "378MHz", provider: "<N/A>", service: "Raw PID Subscription"
2015-03-19 13:16:21.000 [ NOTICE] subscription: 0003: No input source available for subscription "SAT>IP" to channel "none"
2015-03-19 13:16:22.132 [   INFO] subscription: 0003: "SAT>IP" unsubscribing, hostname="192.168.178.133", username="<N/A>", client="LibVLC/2.0.8 (LIVE555 Streaming Media v2011.12.23)"
2015-03-19 13:16:22.133 [   INFO] mpegts: 338MHz in KDG (0x1b45dc0) - deleting
2015-03-19 13:16:22.137 [  ERROR] http: 192.168.178.133: RTSP/1.0 SETUP stream=2/ -- 456
2015-03-19 13:16:30.401 [WARNING] linuxdvb: DRXK DVB-C DVB-T : DVB-C #0 - read() EOVERFLOW
```

**Comment by perexg** [comment]
@9000h : Fixed now.. It was a bit crazy problem.

**Comment by 9000h** [comment]
so, looks better now vlc did stream fta but decryption is not working up to now

**Comment by perexg** [comment]
@9000h : Could you elaborate / show logs ? Can you stream a scrambled service through the standard HTTP streaming ?

**Comment by 9000h** [comment]
Yes non satip streams  work fine with decryption

**Comment by 9000h** [comment]
first normal http stream, second same channel via rtsp satip
```
2015-03-19 21:25:26.570 [   INFO] main: Log started
2015-03-19 21:25:26.599 [   INFO] satips: SAT>IP Server initialized (HTTP 192.168.178.126:9981, RTSP 192.168.178.126:554, descramble 2, muxcnf 0)
2015-03-19 21:25:26.599 [   INFO] satips: SAT>IP Server tuners: DVB-T/T2 0/0, DVB-S/S2 0/0, DVB-C/C2 1/0, ATSC 0, DVB-Cable/AnnexB 0
2015-03-19 21:25:26.617 [   INFO] config: loaded
2015-03-19 21:25:27.601 [   INFO] scanfile: DVB-T - loaded 43 regions with 729 networks
2015-03-19 21:25:27.601 [   INFO] scanfile: DVB-S - loaded 1 regions with 93 networks
2015-03-19 21:25:27.601 [   INFO] scanfile: DVB-C - loaded 16 regions with 51 networks
2015-03-19 21:25:27.601 [   INFO] scanfile: ATSC - loaded 2 regions with 14 networks
2015-03-19 21:25:29.224 [   INFO] linuxdvb: adapter added /dev/dvb/adapter0
2015-03-19 21:25:29.517 [   INFO] dvr: Creating new configuration ''
2015-03-19 21:25:29.517 [WARNING] dvr: Output directory for video recording is not yet configured for DVR configuration "". Defaulting to to "/root". This can be changed from the web user interface.
2015-03-19 21:25:29.517 [WARNING] access: Access control checking disabled
2015-03-19 21:25:29.519 [   INFO] CSA: Using 32bit parallel descrambling
2015-03-19 21:25:29.521 [   INFO] epggrab: module eit created
2015-03-19 21:25:29.521 [   INFO] epggrab: module uk_freesat created
2015-03-19 21:25:29.521 [   INFO] epggrab: module uk_freeview created
2015-03-19 21:25:29.521 [   INFO] epggrab: module viasat_baltic created
2015-03-19 21:25:29.523 [   INFO] capmt: vdr active
2015-03-19 21:25:29.527 [   INFO] capmt: vdr: mode 5 connected to 192.168.178.1:2000 (single)
2015-03-19 21:25:29.541 [   INFO] epggrab: module opentv-ausat created
2015-03-19 21:25:29.542 [   INFO] epggrab: module opentv-skyuk created
2015-03-19 21:25:29.542 [   INFO] epggrab: module opentv-skyit created
2015-03-19 21:25:29.549 [   INFO] capmt: vdr: connected to OSCam v1.20-unstable_svn, build r10629 (mips-linux-uclibc-ssl-libusb), using network protocol_version = 1
2015-03-19 21:25:29.552 [   INFO] epggrab: module pyepg created
2015-03-19 21:25:29.552 [   INFO] epggrab: module xmltv created
2015-03-19 21:25:34.259 [   INFO] epgdb: loaded v2
2015-03-19 21:25:34.259 [   INFO] epgdb:   config     1
2015-03-19 21:25:34.259 [   INFO] epgdb:   channels   0
2015-03-19 21:25:34.259 [   INFO] epgdb:   brands     0
2015-03-19 21:25:34.259 [   INFO] epgdb:   seasons    0
2015-03-19 21:25:34.259 [   INFO] epgdb:   episodes   44865
2015-03-19 21:25:34.259 [   INFO] epgdb:   broadcasts 43662
2015-03-19 21:25:34.320 [ NOTICE] START: HTS Tvheadend version -unknown started, running as PID:13682 UID:0 GID:0, CWD:/usr/src/satip/tvheadend CNF:/root/.hts/tvheadend
2015-03-19 21:25:34.331 [   INFO] mpegts: 378MHz in KDG - tuning on DRXK DVB-C DVB-T : DVB-C #0
2015-03-19 21:25:34.331 [   INFO] subscription: 0001: "epggrab" subscribing on "none", weight: 4, adapter: "DRXK DVB-C DVB-T : DVB-C #0", network: "KDG", mux: "378MHz", provider: "<N/A>", service: "Raw PID Subscription"
2015-03-19 21:25:35.158 [   INFO] AVAHI: Service 'Tvheadend' successfully established.
2015-03-19 21:25:45.123 [   INFO] subscription: 0001: "epggrab" unsubscribing
2015-03-19 21:25:46.000 [   INFO] mpegts: 121MHz in KDG - tuning on DRXK DVB-C DVB-T : DVB-C #0
2015-03-19 21:25:46.000 [   INFO] subscription: 0003: "epggrab" subscribing on "none", weight: 4, adapter: "DRXK DVB-C DVB-T : DVB-C #0", network: "KDG", mux: "121MHz", provider: "<N/A>", service: "Raw PID Subscription"
2015-03-19 21:25:52.382 [   INFO] mpegts: 538MHz in KDG - tuning on DRXK DVB-C DVB-T : DVB-C #0
2015-03-19 21:25:52.386 [   INFO] capmt: vdr: Starting CAPMT server for service "DELUXE MUSIC" on adapter 0 seq 0x0001
2015-03-19 21:25:52.386 [   INFO] subscription: 0005: "HTTP" subscribing on "DELUXE MUSIC", weight: 100, adapter: "DRXK DVB-C DVB-T : DVB-C #0", network: "KDG", mux: "538MHz", provider: "Digital Free", service: "DELUXE MUSIC", profile="pass", hostname="192.168.178.130", username="<N/A>", client="VLC/3.0.0-git LibVLC/3.0.0-git"
2015-03-19 21:25:52.386 [   INFO] subscription: 0003: "epggrab" unsubscribing
2015-03-19 21:26:03.089 [   INFO] subscription: 0005: "HTTP" unsubscribing from "DELUXE MUSIC", hostname="192.168.178.130", username="<N/A>", client="VLC/3.0.0-git LibVLC/3.0.0-git"
2015-03-19 21:26:03.093 [   INFO] capmt: vdr: Removing CAPMT Server from service "DELUXE MUSIC" on adapter 0
2015-03-19 21:26:10.049 [WARNING] satips: 0/EF67D54D/1: create mux DVBC/ANNEX_A freq 538000000 sym 6900000 mod QAM/256 fec NONE
2015-03-19 21:26:10.051 [   INFO] mpegts: 538MHz in KDG - tuning on DRXK DVB-C DVB-T : DVB-C #0
2015-03-19 21:26:10.052 [   INFO] opentv-skyit: registering mux 538MHz in KDG
2015-03-19 21:26:10.248 [   INFO] subscription: 0008: "SAT>IP" subscribing on "none", weight: 100, adapter: "DRXK DVB-C DVB-T : DVB-C #0", network: "KDG", mux: "538MHz", provider: "<N/A>", service: "Raw PID Subscription", hostname="192.168.178.130", username="<N/A>", client="LibVLC/3.0.0-git (LIVE555 Streaming Media v2014.07.25)"
2015-03-19 21:26:13.183 [   INFO] mpegts: 538MHz in KDG scan complete
2015-03-19 21:26:24.696 [   INFO] subscription: 0008: "SAT>IP" unsubscribing, hostname="192.168.178.130", username="<N/A>", client="LibVLC/3.0.0-git (LIVE555 Streaming Media v2014.07.25)"
2015-03-19 21:26:24.704 [   INFO] mpegts: 538MHz in KDG (0x20f4cd0) - deleting
```

**Comment by perexg** [comment]
The problem is that the mux is not matched (look to WARNING) and a new, temporary mux is created for the SAT>IP session. In this case the service is not descrambled, because there are not attached services until the scan is complete. Does all parameters in the 538Mhz mux match to the satip rtsp request ?

**Comment by 9000h** [comment]
this is the request, and works with all satip server I can test
rtsp://192.168.178.126:554/?freq=538.000&msys=dvbc&sr=6900&mtype=256qam&pids=0,118,2351,2352

**Comment by perexg** [comment]
Yep, but I don't know parameters of your 538Mhz mux defined in tvheadend.. It should be Annex A, req 538000000 sym 6900000 mod QAM/256 fec NONE .

**Comment by 9000h** [comment]
seem like the issue but why not using auto 
screen shot 2015-03-19 at 22 14 04

**Comment by 9000h** [comment]
the spec has no fec for dvb-c 

Example DVB-C Query:
rtsp://192.168.128.5/?freq=623.25&msys=dvbc&mtype=256qam&sr=6900&specinv=0&pids=0,16,50,2
01,301

**Comment by perexg** [comment]
It seems another issue. The FEC is not matched. Could you retry with the latest fix now ?

**Comment by 9000h** [comment]
works
```
2015-03-19 23:42:36.147 [   INFO] mpegts: 538MHz in KDG - tuning on DRXK DVB-C DVB-T : DVB-C #0
2015-03-19 23:42:36.152 [   INFO] subscription: 0003: "SAT>IP" subscribing on "none", weight: 100, adapter: "DRXK DVB-C DVB-T : DVB-C #0", network: "KDG", mux: "538MHz", provider: "<N/A>", service: "Raw PID Subscription", hostname="192.168.178.130", username="<N/A>", client="LibVLC/3.0.0-git (LIVE555 Streaming Media v2014.07.25)"
2015-03-19 23:42:36.152 [   INFO] subscription: 0001: "epggrab" unsubscribing
2015-03-19 23:42:36.152 [   INFO] capmt: vdr: Starting CAPMT server for service "DELUXE MUSIC" on adapter 0 seq 0x0001
2015-03-19 23:42:36.153 [   INFO] subscription: 0004: "SAT>IP Slave/KDG/538MHz/DELUXE MUSIC" subscribing on "none", weight: 0, adapter: "DRXK DVB-C DVB-T : DVB-C #0", network: "KDG", mux: "538MHz", provider: "Digital Free", service: "DELUXE MUSIC"
```

**Comment by retrofan1979** [comment]
I tried SAT>IP server from Tvheadend with HDHomeRun device and it works fine, except Tvheadend some reports transport errors and continuity errors at random when changing channels. Not when streaming, only when changing channels as far as I can see.
I noticed the option "Fast input switch" is not available for internal SAT>IP server of Tvheadend. Could this be the problem?

**Pull request merged**
