### PR TITLE
Fix creation of CA Client type 'AES128 ECB Constant Code Word' (Issue #5119)

### PR DESCRIPTION
**Pull request by irgendsontyp**
Fixes https://tvheadend.org/issues/5119

### CODE REVIEW

**Comment by irgendsontyp** [comment]
Btw., what happens to the corresponding issue in the tvheadend bug tracker if you accept the PR? https://tvheadend.org/issues/5119 in this case.

**Comment by perexg** [comment]
BTW: Write 'fixes #5119' or 'issue #5119' to the subject of the commit to close or connect to the issue in the bug tracker next time. Thanks.

**Comment by irgendsontyp** [comment]
@perexg Does the bug tracker automatically close the issue when I add "fixes #..." or "issue #..." to the commit? 

The corresponding bug for my other PR was not closed, too (https://tvheadend.org/issues/5126). 

Also, your commit "ea9159ecbdc695a4e717c420c2dd7b4d926cb2b9" fixes https://tvheadend.org/issues/5087 but 5087 is still in "New" state.

**Comment by perexg** [comment]
"fixes #" closes the ticket as fixed and "issue #" just assigns the commit to the bug

**Comment by irgendsontyp** [comment]
Is it better to use "issue #" then, as we as non-commiter contributors can never be sure for the PR to be accepted? Thus, linking the commit to the bug is always right but closing the issue before the commit is merged doesn't make sense to me.

**Comment by perexg** [comment]
Note that the bug linking is proceed when the commit is merged (validated), thus you can mark the commit as you like. The "fixes" word saves my time when it's an obvious code fix.

**Pull request merged**
