### PR TITLE
HTSP: deliver 'comment' with autorecEntry(Add|Update), timerecEntry(A…

### PR DESCRIPTION
**Pull request by ksooo**
…dd|Update). Allow setting 'comment' with 'updateDvrEntry'.

Bump HTSP version to 41.

I need this for extended dvr property support in upcoming Kodi / pvr.hts release.

### CODE REVIEW

**Comment by DeltaMikeCharlie** [comment]
@Flole998 - PR #1753 also bumps the API version to 41.  Perhaps both PRs could be merged to the same time as, IMNSHO, there is no need to increment the version number for these changes so close together.

**Comment by ksooo** [comment]
It’s just a number. No further impact/ consequences on increase. I don’t see the need to couple unrelated things just to save a bump. Even more, more fine grained bumps give more control on client side.

**Comment by Flole998** [comment]
This doesn't compile (and the version number needs to be increased as #1753 has been merged).

**Comment by ksooo** [comment]
> This doesn't compile 

 Oopps, my bad. Sorry. Fixed.
 
> (and the version number needs to be increased as https://github.com/tvheadend/tvheadend/pull/1753 has been merged).

 Done.

**Comment by ksooo** [comment]
@Flole998 I will update the HTSP specs documentation once this PR has been merged.

**Comment by ksooo** [comment]
> I will update the HTSP specs documentation once this PR has been merged.

Done.

**Pull request merged**
