### PR TITLE
Fix detect AC3+ audio track, fixes#5684

### PR DESCRIPTION
**Pull request by SqTER-PL**

### CODE REVIEW

**Comment by Trujulu** [comment]
8feacbed6488d6eabd3862937c6167a4
Tested and working for 4Fun TV.

**Comment by Trujulu** [comment]
Look:

Oscam is using 0xCC as E-AC3
http://www.streamboard.tv/oscam/changeset/11544

**Comment by SqTER-PL** [comment]
I don't know if it's good. I didn't see the stream with this ID '0xCC'
See how VLC does it.
Please analyze this file https://github.com/videolan/vlc/blob/master/modules/demux/mpeg/ts_psi.c

Take a look at this line: https://github.com/videolan/vlc/blob/master/modules/demux/mpeg/ts_psi.c#L1525

ATSC Standard: Digital Audio Compression (AC-3, E-AC-3) https://www.atsc.org/wp-content/uploads/2015/03/A52-201212-17.pdf  (See page 259)

**Comment by SqTER-PL** [comment]
> Look:
> 
> Oscam is using 0xCC as E-AC3
> http://www.streamboard.tv/oscam/changeset/11544

Oscam also uses 0x87
http://www.streamboard.tv/oscam/browser/trunk/module-dvbapi.c?rev=11544#L81

**Comment by SqTER-PL** [comment]
0xCC may be helpful. This is 'descriptor_tag'
See [documentation](https://www.atsc.org/wp-content/uploads/2015/03/A52-201212-17.pdf) page 263 (descriptor_tag - The value assigned to the E-AC-3_audio_descriptor () tag is 0xCC)

I don't know how to use it here. Maybe somebody else say something.

**Comment by perexg** [comment]
Fixed in 7f090c9829a98427692e06a907c3197ea7230071 , keep just my original proposal. No capmt / DVB_DESC_EAC3 changes.

**Pull request closed without merging**
