### PR TITLE
Makefile(s): fix libmfx support

### PR DESCRIPTION
**Pull request by lekma**

### CODE REVIEW

**Comment by lekma** [comment]
might be needed:
sudo apt-get install libva-dev autoconf libtool

**Comment by L-S-D** [comment]
on Debian, libtool-bin is also needed
still not working for me, have to check if Intel Media SDK is installed correctly

**Comment by lekma** [comment]
what is not working?
does it build?

**Comment by L-S-D** [comment]
it is building fine, no problem with that, but I can't use QSV, see http://tvheadend.org/issues/3080

**Comment by perexg** [comment]
Merged. Thanks.

**Pull request closed without merging**
