### PR TITLE
transcode: update to latest FFmpeg API

### PR DESCRIPTION
**Pull request by mlauss**
This patch updates the transcoder to the the latest ffmpeg/libav API, fixes
build against ffmpeg-2.9/git

Beware: upstream ffmpeg removed the long deprecated deinterlace module,
so deinterlacing is no longer done in tvheadend.

Signed-off-by: Manuel Lauss <manuel.lauss@gmail.com>

### CODE REVIEW

**Comment by CvH** [comment]
@mlauss deinterlace is somewhat important (if you stream to lowend devices)
any alternatives ?

**Comment by mlauss** [comment]
Probably need to implement a way to hook the vf_yadif filter before scaling/encoding.
However I have no idea (yet) how to do that just now.
The old "avpicture_deinterlace()" algorithm is gone, and not coming back I assume,
that's why I removed it.

**Comment by mlauss** [comment]
Looks like the whole transcode code should be overhauled to create a filter chain.
I'll look into it, but no promises :)

**Comment by mlauss** [comment]
I've implemented the filter chain method instead, so this pull request is obsolete.

**Pull request closed without merging**
