### PR TITLE
Merge pull request #1 from seirsandyk/master

### PR DESCRIPTION
**Pull request by galeneca**
Ivan

### CODE REVIEW

**Comment by galeneca** [comment]
#

**Comment by galeneca** [comment]
### 

> **__**

**Comment by galeneca** [comment]
[tvheadend-3.4patch1.tar.gz](https://github.com/tvheadend/tvheadend/files/570816/tvheadend-3.4patch1.tar.gz)

**Comment by CvH** [comment]
@galeneca could you pls stop spamming the official tvheadend github repo? 
I guess you do something wrong !

**Comment by perexg** [comment]
@galeneca : STOP DOING THAT !!! YOU ARE TRYING TO PROPOSE INVALID PULL REQUESTS TO THE MAIN TVHEADEND REPOSITORY !!!

**Pull request closed without merging**
