### PR TITLE
Add support for vendor DISEQC command sequences.

### PR DESCRIPTION
**Pull request by hselasky**
Work in progress.

Signed-off-by: Hans Petter Selasky <hps@selasky.org>

### CODE REVIEW

**Comment by Flole998** [comment]
Have you finished your work on this or is this still work in progress?

**Comment by hselasky** [comment]
It works for my use, but you may want to review it.

**Comment by Flole998** [comment]
Please document the usage your new feature in the appropriate file in `docs/` and not in the source code so it will be shown at the appropriate location in the Webinterface.

**Comment by Flole998** [comment]
Closing due to inactivity

**Pull request closed without merging**
