### PR TITLE
epggrab: first change parameters, then submit to queue (fixes loop)

### PR DESCRIPTION
**Pull request by danielkucera**

### CODE REVIEW

**Comment by perexg** [comment]
What do you like to fix with this? The access to epggrab_ota_pending tail queue should be always protected using the global_lock mutex.

**Comment by danielkucera** [comment]
It happens to me that epggrab stucks in a loop:
```
Mar  7 02:04:01 server tvheadend[10108]: mpegts: 10716H in upc - tuning on Conexant CX24117/CX24132 #0 : DVB-S #0
Mar  7 02:04:01 server tvheadend[10108]: 2018-03-07 02:04:01.061 [   INFO] mpegts: 10716H in upc - tuning on Conexant CX24117/CX24132 #0 : DVB-S #0
Mar  7 02:04:01 server tvheadend[10108]: subscription: 0014: "epggrab" subscribing to mux "10716H", weight: 4, adapter: "Conexant CX24117/CX24132 #0 : DVB-S #0", network: "upc", service: "Raw PID Subscription"
Mar  7 02:04:01 server tvheadend[10108]: 2018-03-07 02:04:01.415 [   INFO] subscription: 0014: "epggrab" subscribing to mux "10716H", weight: 4, adapter: "Conexant CX24117/CX24132 #0 : DVB-S #0", network: "upc", service: "Raw PID Subscription"
Mar  7 02:04:01 server tvheadend[10108]: mpegts: 10747H in upc - tuning on Conexant CX24117/CX24132 #1 : DVB-S #0
Mar  7 02:04:01 server tvheadend[10108]: 2018-03-07 02:04:01.432 [   INFO] mpegts: 10747H in upc - tuning on Conexant CX24117/CX24132 #1 : DVB-S #0
Mar  7 02:04:01 server tvheadend[10108]: subscription: 0015: "epggrab" subscribing to mux "10747H", weight: 4, adapter: "Conexant CX24117/CX24132 #1 : DVB-S #0", network: "upc", service: "Raw PID Subscription"
Mar  7 02:04:01 server tvheadend[10108]: 2018-03-07 02:04:01.819 [   INFO] subscription: 0015: "epggrab" subscribing to mux "10747H", weight: 4, adapter: "Conexant CX24117/CX24132 #1 : DVB-S #0", network: "upc", service: "Raw PID Subscription"
Mar  7 02:04:01 server tvheadend[10108]: mpegts: 10809H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 02:04:01 server tvheadend[10108]: 2018-03-07 02:04:01.826 [   INFO] mpegts: 10809H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 02:04:02 server tvheadend[10108]: diseqc: failed to set voltage (e=Connection timed out)
Mar  7 02:04:02 server tvheadend[10108]: 2018-03-07 02:04:02.187 [  ERROR] diseqc: failed to set voltage (e=Connection timed out)
Mar  7 02:04:02 server kernel: [630292.954223] i2c i2c-8: cx24117: demod0 LNB not ready
Mar  7 02:04:02 server tvheadend[10108]: mpegts: 10809H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 02:04:02 server tvheadend[10108]: 2018-03-07 02:04:02.229 [   INFO] mpegts: 10809H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 02:04:02 server tvheadend[10108]: diseqc: failed to set voltage (e=Connection timed out)
Mar  7 02:04:02 server tvheadend[10108]: 2018-03-07 02:04:02.587 [  ERROR] diseqc: failed to set voltage (e=Connection timed out)
Mar  7 02:04:02 server tvheadend[10108]: mpegts: 10841H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 02:04:02 server tvheadend[10108]: 2018-03-07 02:04:02.588 [   INFO] mpegts: 10841H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 02:04:02 server kernel: [630293.354187] i2c i2c-8: cx24117: demod0 LNB not ready
Mar  7 02:04:02 server tvheadend[10108]: diseqc: failed to set voltage (e=Connection timed out)
Mar  7 02:04:02 server tvheadend[10108]: 2018-03-07 02:04:02.947 [  ERROR] diseqc: failed to set voltage (e=Connection timed out)
Mar  7 02:04:02 server kernel: [630293.714156] i2c i2c-8: cx24117: demod0 LNB not ready
Mar  7 02:04:02 server tvheadend[10108]: mpegts: 10872H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 02:04:02 server tvheadend[10108]: 2018-03-07 02:04:02.964 [   INFO] mpegts: 10872H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 02:04:04 server tvheadend[10108]: diseqc: failed to set voltage (e=Connection timed out)
Mar  7 02:04:04 server tvheadend[10108]: 2018-03-07 02:04:04.527 [  ERROR] diseqc: failed to set voltage (e=Connection timed out)
Mar  7 02:04:04 server tvheadend[10108]: mpegts: 10903H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 02:04:04 server tvheadend[10108]: 2018-03-07 02:04:04.527 [   INFO] mpegts: 10903H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 02:04:04 server kernel: [630295.294003] i2c i2c-8: cx24117: demod0 LNB not ready
Mar  7 02:04:04 server tvheadend[10108]: diseqc: failed to set voltage (e=Connection timed out)
Mar  7 02:04:04 server tvheadend[10108]: 2018-03-07 02:04:04.887 [  ERROR] diseqc: failed to set voltage (e=Connection timed out)
```

**Comment by danielkucera** [comment]
I've applied it just one hour ago and will test it if it really helps. Usually this happened few times a day so if the loop doesn't appear until tomorrow evening, I'll post an update.

**Comment by perexg** [comment]
There's some hardware/driver issue with third tuner. TVH tries to allocate all tuners for the epggrab (you may restrict the tuner list for this job - see the tuner config). Anyway, try to resolve the issue with the problematic tuner.

**Comment by danielkucera** [comment]
Ok, the patch did not help. I use TBS6984 which is a 4 tuner DVB-S2 card. Let's say one tuner is faulty (accualy it is not connected only). The problem is, that when tvh starts beating to it with epggrab, all other tuners stop working and the web interfaces also stops responding. I guess this should not happen. At least I know how to trigger it now (I don't have to wait for it to happen).
When it's locked up, it only logs following without end:
```
Mar  7 22:14:37 server tvheadend[17878]: 2018-03-07 22:14:37.883 [  ERROR] diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:37 server tvheadend[17878]: 2018-03-07 22:14:37.883 [   INFO] mpegts: 12284H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:37 server tvheadend[17878]: mpegts: 12284H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:37 server kernel: [702922.682331] i2c i2c-8: cx24117: demod0 LNB not ready
Mar  7 22:14:39 server tvheadend[17878]: diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:39 server tvheadend[17878]: 2018-03-07 22:14:39.443 [  ERROR] diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:39 server tvheadend[17878]: 2018-03-07 22:14:39.443 [   INFO] mpegts: 12284H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:39 server tvheadend[17878]: mpegts: 12284H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:39 server kernel: [702924.242205] i2c i2c-8: cx24117: demod0 LNB not ready
Mar  7 22:14:41 server tvheadend[17878]: diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:41 server tvheadend[17878]: 2018-03-07 22:14:41.007 [  ERROR] diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:41 server tvheadend[17878]: 2018-03-07 22:14:41.007 [   INFO] mpegts: 12322H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:41 server tvheadend[17878]: mpegts: 12322H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:41 server kernel: [702925.806093] i2c i2c-8: cx24117: demod0 LNB not ready
Mar  7 22:14:41 server tvheadend[17878]: diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:41 server tvheadend[17878]: 2018-03-07 22:14:41.367 [  ERROR] diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:41 server tvheadend[17878]: 2018-03-07 22:14:41.367 [   INFO] mpegts: 12322H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:41 server tvheadend[17878]: mpegts: 12322H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:41 server kernel: [702926.166064] i2c i2c-8: cx24117: demod0 LNB not ready
Mar  7 22:14:41 server tvheadend[17878]: diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:41 server tvheadend[17878]: 2018-03-07 22:14:41.727 [  ERROR] diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:41 server tvheadend[17878]: 2018-03-07 22:14:41.727 [   INFO] mpegts: 12360H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:41 server tvheadend[17878]: mpegts: 12360H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:41 server kernel: [702926.526039] i2c i2c-8: cx24117: demod0 LNB not ready
Mar  7 22:14:42 server tvheadend[17878]: diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:42 server tvheadend[17878]: 2018-03-07 22:14:42.087 [  ERROR] diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:42 server tvheadend[17878]: 2018-03-07 22:14:42.087 [   INFO] mpegts: 12360H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:42 server tvheadend[17878]: mpegts: 12360H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:42 server kernel: [702926.886019] i2c i2c-8: cx24117: demod0 LNB not ready
Mar  7 22:14:42 server tvheadend[17878]: diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:42 server tvheadend[17878]: 2018-03-07 22:14:42.447 [  ERROR] diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:42 server tvheadend[17878]: 2018-03-07 22:14:42.447 [   INFO] mpegts: 12399H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:42 server tvheadend[17878]: mpegts: 12399H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:42 server kernel: [702927.245993] i2c i2c-8: cx24117: demod0 LNB not ready
Mar  7 22:14:42 server tvheadend[17878]: diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:42 server tvheadend[17878]: 2018-03-07 22:14:42.807 [  ERROR] diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:42 server tvheadend[17878]: 2018-03-07 22:14:42.807 [   INFO] mpegts: 12437H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:42 server tvheadend[17878]: mpegts: 12437H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:42 server kernel: [702927.605959] i2c i2c-8: cx24117: demod0 LNB not ready
Mar  7 22:14:43 server tvheadend[17878]: diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:43 server tvheadend[17878]: 2018-03-07 22:14:43.167 [  ERROR] diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:43 server tvheadend[17878]: 2018-03-07 22:14:43.167 [   INFO] mpegts: 12476H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:43 server tvheadend[17878]: mpegts: 12476H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:43 server kernel: [702927.965940] i2c i2c-8: cx24117: demod0 LNB not ready
Mar  7 22:14:43 server tvheadend[17878]: diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:43 server tvheadend[17878]: 2018-03-07 22:14:43.527 [  ERROR] diseqc: failed to set voltage (e=Connection timed out)
Mar  7 22:14:43 server tvheadend[17878]: 2018-03-07 22:14:43.527 [   INFO] mpegts: 12527H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:43 server tvheadend[17878]: mpegts: 12527H in upc - tuning on Conexant CX24117/CX24132 #2 : DVB-S #0
Mar  7 22:14:43 server kernel: [702928.325924] i2c i2c-8: cx24117: demod0 LNB not ready
```
The only solution I have so far is to restart tvh.

**Comment by danielkucera** [comment]
gdb says following:
```
(gdb) fin
Run till exit from #0  mpegts_mux_subscribe (mm=mm@entry=0x56084df8c720, mi=mi@entry=0x0, name=name@entry=0x56084ac913c6 "epggrab", weight=weight@entry=4, 
    flags=flags@entry=33152) at src/input/mpegts/mpegts_mux.c:1388
0x0000560849f9b684 in epggrab_ota_kick_cb (p=<optimized out>) at src/epggrab/otamux.c:573
573	  if ((r = mpegts_mux_subscribe(mm, NULL, "epggrab",
Value returned is $1 = 203
```

**Comment by danielkucera** [comment]
I've updated the patch. This really fixes the tuning loop. It's tested and works. Is it acceptable?

**Comment by perexg** [comment]
Yes, it looks like a more correct fix. I applied it, but it's not the ideal solution. Only the failing adapter (input) should be skipped.

**Pull request closed without merging**
