### PR TITLE
Audio-only MPEG elementary stream muxer

### PR DESCRIPTION
**Pull request by Hypfer**
To implement Feature #3953 I've taken this old PR ( https://github.com/tvheadend/tvheadend/pull/263 ) and made it work with the current tree.

### CODE REVIEW

**Comment by piotrasd** [comment]
+1 to merge

**Comment by DJBenson** [comment]
+2 👍

**Comment by ulope** [comment]
Yes please! This would make streaming satellite radio so much easier.

**Comment by nightwatcher74** [comment]
+3 👍

**Comment by perexg** [comment]
Merged with cleanups and extensions. Please, report any bugs to the bugtracker. Thanks.

**Comment by ulope** [comment]
Works perfectly. Thanks!

**Comment by piotrasd** [comment]
for me too, One question ... there is any way to save audio track to any other format/container than .bin ??? and why there is no option to choose ? :(

**Comment by perexg** [comment]
@piotrasd : The mime / suffix auto detection did't work. It's fixed in 37ef4b8afadc35d3d650220f8cbe90b26b57d35a .

**Comment by piotrasd** [comment]
@perexg nice reaction !!! wow ! and big thanks for fix !

**Comment by snickers2k** [comment]
is this also possible for mp3? i can't find an option for mp3, but need this for Fritz!Fon (DECT Fon with mp3 Radio-Support). thanks

**Comment by perexg** [comment]
@snickers2k : If you have any issue, create a bug with a description what does not work for you.

**Pull request closed without merging**
