### PR TITLE
DVB-S2/T2 multistream support.

### PR DESCRIPTION
**Pull request by crazycat69**

### CODE REVIEW

**Comment by crazycat69** [comment]
DVB-S2 Multiple Input Stream support.
DVB-T2 MultiPLP support.

**Comment by perexg** [comment]
If PLS MODE and PLS CODE is dvb-s2 specific, it should be moved to the dvb_qpsk_config_t structure..

**Comment by perexg** [comment]
Anyway, thanks for this patch. It looks good.

**Comment by crazycat69** [comment]
But Pilot and Rolloff also defined as common fields of dvb_mux_conf struct ?

**Comment by perexg** [comment]
Yes, hoping that these values can be reused for other modulations / signalling in future. You may keep them "global", if you think that's the right place. I don't have a strong objection for it.

**Comment by perexg** [comment]
Merged. Thanks.

**Pull request closed without merging**
