### PR TITLE
Tooltips

### PR DESCRIPTION
**Pull request by mpmc**
Here is another bunch of tooltips/descriptions!
@perexg / @adamsutton You may want to cherry pick these as I goofed and did a merge in the middle :/

### CODE REVIEW

**Comment by adamsutton** [comment]
@mpmc just rebase them onto master

$ git rebase upstream/master
$ git push -f origin HEAD

**Comment by mpmc** [comment]
@adamsutton I'd prefer to keep them separate in case I majorly screw up as I'm still getting my head around git :)

**Comment by perexg** [comment]
I picked all commits.

**Comment by mpmc** [comment]
Thanks perexg :)

**Pull request closed without merging**
