### PR TITLE
Silcence x265 warnings

### PR DESCRIPTION
**Pull request by Flole998**

### CODE REVIEW

**Comment by CvH** [comment]
@Flole998 could you pls name your commits according to what they do (like the PR description)?
Browsing at the commit history and seeing `Add patch to Makefile` or `Add patch` is rather useless.

**Comment by Flole998** [comment]
@CvH That's why it got squashed together and is now named "Silence x265 warnings"

**Comment by CvH** [comment]
just for clarification, you merged it and after merging you squashed it at master, then force pushed master?

**Comment by Flole998** [comment]
No, I made a pull request and used the "squash and merge" option to make it a single commit in master and give it a meaningful name. Otherwise I could have committed directly without making a PR.

**Pull request merged**
