### PR TITLE
Disable legacy and deprecated OSCam capmt modes

### PR DESCRIPTION
**Pull request by manio**
I think it would be nice to start disabling those modes...

### CODE REVIEW

**Comment by Jalle19** [comment]
@manio I'd like this as well, but I think all the code should be removed too, not just ifed out.

**Comment by manio** [comment]
@Jalle19 
Me too, but the ifdefing was a @perexg idea, when we was discussing it on IRC. The plan was to disable it the way to to be able to easily revert in case of problems, then after some time when no one complains, clean the code up.

@perexg any news on this?

**Comment by perexg** [comment]
I plan to merge this to 4.3 .

**Comment by Trujulu** [comment]
We are on 4.3 now :o

**Comment by perexg** [comment]
Removed in 2403a543a9aef03266edff004c10e2458acaeb30 .

**Comment by manio** [comment]
Thanks! :)

**Comment by renedis** [comment]
Not happy.. Still using the rev-9756 mode with an Oscam/Irdeto setup. Does not work anymore!

**Comment by manio** [comment]
Any reason to not updating your oscam?

**Comment by renedis** [comment]
Oscam is running on:
OSCam: 1.20-unstable_svn Build: r11401 with rev-9756 and "/tmp/camd.socket" option.

When using "OSCam new pc-nodmx (rev >= 10389)" the descrambler only works the first time (first channel). After that TVHeadend needs to be restarted in order to descramble again.

I'm not the first with this issue:
https://tvheadend.org/issues/4038

**Comment by perexg** [comment]
Try the standard TCP connection instead named socket. Appearently, the oscam code remains somewhat broken for the named socket.

**Comment by renedis** [comment]
Took some investigation but got TCP connection working now.

**Pull request closed without merging**
