### PR TITLE
Add request feature #5009

### PR DESCRIPTION
**Pull request by pablozg**
I think it can useful for everyone.

### CODE REVIEW

**Comment by pablozg** [comment]
It's not correct, the field "channel" shows the number and the name, so don't worry.

channel

**Comment by ProfYaffle** [comment]
Okay - I'll relax a little, so thanks! - although doesn't that screw up alpha sorting by channel name?

**Comment by pablozg** [comment]
The field sorting is not affected. ;-)

**Comment by ProfYaffle** [comment]
I'll shut up and go away, then :grin:

**Comment by perexg** [comment]
It's incomplete. You should handle the empty case (when empty uuid is returned in the channel field - it's the case when channel is removed, but the recordings have saved the channel name in 'channelname' field which is used currently).  See 'renderer:' functions in src/webui/static/app/dvr.js for examples.

**Comment by pablozg** [comment]
Before to make the changes over 'dvrdb.c' file, I tried to do the dvr.js aproach with the rendered option, but only was able to get the field but not the number, now I have to learn of your code for the next time. Thanks perexg.

P.D. Feel free to close this PR

**Comment by perexg** [comment]
Merged your 222c8541b981e6db6fa9f2d59f2553235bbc1c4b and fixed missing removed channel names in 163322179186fcadbef18145ad10a7818e2b094a .

**Pull request closed without merging**
