### PR TITLE
fix .doozer.json to reflect recent changes to configure

### PR DESCRIPTION
**Pull request by lekma**

### CODE REVIEW

**Comment by lekma** [comment]
@perexg it seems my search for libffmpeg_static ignored hidden files, sorry about that

**Comment by perexg** [comment]
Merged.

**Comment by perexg** [comment]
BTW: The builds are failing - https://tvheadend.org/builds/tvheadend .

**Comment by lekma** [comment]
@perexg try disabling parallel building for ffmpeg_static

**Comment by perexg** [comment]
It won't help. Parallel build is fine. I found this for precise:

  CMake 2.8.8 or higher is required.  You are running version 2.8.7

**Comment by perexg** [comment]
OK, the $(LIB_ROOT)/$(FFMPEG)/.tvh_tmp is the culprit.. What's this?

**Comment by lekma** [comment]
@perexg  .tvh_tmp is a temp build of ffmpeg needed by libx264 to enable swscale and avfilter.
Now that you seem to have a handle on the automatic builds would you mind putting it back (at least  to confirm it was the culprit)?

**Pull request closed without merging**
