### PR TITLE
Update config for Fedora 37/38

### PR DESCRIPTION
**Pull request by rubdos**
I'm not sure whether Doozer is still relevant, now that RPMFusion is shipping rather recent versions.

### CODE REVIEW

**Comment by Flole998** [comment]
Doozer is no longer used. If you want you can try to get GitHub actions to work for Fedora, then we can publish the RPMs to cloudsmith where all the Debian packages are aswell.

**Comment by rubdos** [comment]
> try to get GitHub actions to work for Fedora

Attempt in cb86eb8.

**Comment by rubdos** [comment]
They don't even seem to start :-/

How do we find out the reason? I'm more used to Gitlab CI which is quite a bit more verbose.

**Comment by Flole998** [comment]
That's because "fedora-latest" is most likely not a valid image name that GitHub actions can use. There is a list somewhere and you need to choose one of the options from that list, otherwise it will just wait forever until the specified one becomes available (which might never happen).

**Pull request merged**
