### PR TITLE
macOS compatibility modifications

### PR DESCRIPTION
**Pull request by mgriesslehner**
As discussed in #4279 i will share my workaround to compile tvheadend on macOS with you. The timing_mach.c and timing_mach.h i have downloaded from another github project "PosixMachTiming " from "ChisholmKyle " (https://github.com/ChisholmKyle/PosixMachTiming).

### CODE REVIEW

**Comment by vicegold** [comment]
@mgriesslehner Could you provide a compiled build? I can't compile it on macOS, even with your changes.

**Comment by Trujulu** [comment]
As @perexg told me, these commits has something wrong...

**Comment by mgriesslehner** [comment]
Dear Laurids,

it Is nice to hear that anyone else is interesting to run tvheadend on macOS. Unfortunately I cannot provide any binaries, but perhaps I can help if you are able to share some details about the error with me.
About three months ago i have canceled my attempts to get running tvheadend on macOS, because I was not able to fix the architecture-error while compiling: https://tvheadend.org/issues/4284 <https://tvheadend.org/issues/4284>.

Nice greetings from Austria,
Markus

**Comment by chris299** [comment]
@mgriesslehner did you get it to work? I would be interessted in your solution...

kind regards from Germany
Christoph

**Comment by Vaoske** [comment]
Hi Christoph,

I takes al lot of time, but no results. I ‘m now using dvblink with OSCAM and MDJAPI plugins (http://forum.dvblogic.com/viewtopic.php?f=56&t=31946 <http://forum.dvblogic.com/viewtopic.php?f=56&t=31946>) which works great!

Greets from The Netherlands,

Remko Faes

**Comment by perexg** [comment]
I merged more complete solution: #1043 .

**Pull request closed without merging**
