### PR TITLE
Raw audio stream muxer

### PR DESCRIPTION
**Pull request by linuxstb**
This still needs a bit of cleanup, but it's working for me to stream or record the first audio stream in a service (i.e. a Radio station, but can also be used for recording/streaming audio from a TV channel) as a raw MPEG/AC3/AAC audio stream (i.e. no container at all).

NOTE: Please ignore the 6944425 commit, not sure how that got in here...

### CODE REVIEW

**Comment by piotrasd** [comment]
@linuxstb can i please rebase ... ?

**Comment by piotrasd** [comment]
i record many tvshows  or movies just for audio (but alwayes i must manual extract from full record) so this is perfect solution, i hope @perexg you find time to add this

**Comment by Hypfer** [comment]
https://github.com/tvheadend/tvheadend/pull/888 Here's a new version of this PR.

**Comment by perexg** [comment]
Merged into 4.1 (Hypher) - 81056b1a9e4b5a2fc00906c8d7db0251254dec21 , b848597d0b3b86fc4eaae71264f01a6338597567

**Pull request closed without merging**
