### PR TITLE
Remove EOL/unmaintained build targets & add bullseye

### PR DESCRIPTION
**Pull request by mpmc**
I've removed EOL distros and those that are no longer maintained by anyone. Fedora, Centos etc used to be under @perexg's eye however it sadly appears he's no longer able to maintain them? 

Please don't commit without discussing these changes first. Thanks.

### CODE REVIEW

**Comment by Flole998** [comment]
I think everything that still builds should stay in until it breaks, if it's an old distro and no easy fix it can be kicked out then.

**Comment by Saentist** [comment]
Ubuntu 14.04 aka Trusty
cannot be build after latest ffmpeg update

There is no code tags for that

**Comment by mpmc** [comment]
> 
> 
> I think everything that still builds should stay in until it breaks, if it's an old distro and no easy fix it can be kicked out then.

In that case you can just cherry-pick the bullseye commits :)

**Comment by mpmc** [comment]
OK, i'll close this and rework it :)

**Pull request closed without merging**
