### PR TITLE
update to libvpx 1.14.0

### PR DESCRIPTION
**Pull request by uknunknown**
update to libvpx 1.14.0

### CODE REVIEW

**Comment by uknunknown** [comment]
I verified sw transcoding to VP8 and VP9.

**Comment by uknunknown** [comment]
Someone with aarch64 system has to investigate the failures :( .

**Comment by chewitt** [comment]
> Someone with aarch64 system has to investigate the failures

In English this reads as "not my problem" but as the pull-request submitter, it is your responsibility to investigate why the proposed change fails and to find any required fixes. Hopefully the meaning was just "lost in translation" and you really meant to ask for community help on figuring out the issue?

**Comment by CvH** [comment]
Likewise gcc is too old and does not support these instructions that libvpx tries to compile at aarch64.
Thats the fun of running bleeding edge at dead distros.

```
2024-01-18 v1.14.0 "Venetian Duck"

  This release drops support for old C compilers, such as Visual Studio 2012
  and older, that disallow mixing variable declarations and statements (a C99
  feature). It adds support for run-time CPU feature detection for Arm
  platforms, as well as support for darwin23 (macOS 14).
  ```

**Comment by Flole998** [comment]
> Thats the fun of running bleeding edge at dead distros.

How is Ubuntu 20.04 "dead"? It's not even "End of Standard Support". Even Ubuntu 16.04 is not "End of Life" yet. Not even Ubuntu 14.04 (which we aren't even compiling for anymore) is "End of Life" at this point.

**Comment by mralapete** [comment]
> > Thats the fun of running bleeding edge at dead distros.
> 
> How is Ubuntu 20.04 "dead"? It's not even "End of Standard Support". Even Ubuntu 16.04 is not "End of Life" yet. Not even Ubuntu 14.04 (which we aren't even compiling for anymore) is "End of Life" at this point.

Seems these decisions may be out of your hands now. I expected a few “hand grenades” to be thrown into the mix upon the recent announcement of the changes to the TVH project. Some of us do use older versions of Linux distributions which now appear to be in the crosshairs for deprecation.

**Comment by Flole998** [comment]
Who said, that anything will be deprecated? And as far as I am concerned I think it is (still) my decision which OS's are in the CI and what changes are merged and what changes aren't. There are just more people who could take over in case I get hit by a bus or whatever, and those people are also taking care of other non-code-related tasks like migrating the issue tracker to GitHub, operating/migrating/archiving the forum and taking care of the domain registration, signing up for providers that offer free services for open-source projects and their maintainers, maintaining a publicly accessible list of services we are using for transparency and so on. Or in different words: Various things that should be done but that I don't really have time for.

I "like" the idea of re-purposing old hardware and I know from personal experience that it often comes with outdated operating systems. So I am trying to provide packages for old distributions as long as somehow possible with reasonable effort.

**Comment by CvH** [comment]
> Even Ubuntu 16.04 is not "End of Life" yet. Not even Ubuntu 14.04 (which we aren't even compiling for anymore) is "End of Life" at this point.

Ubuntu 16.04 uses a 9 year old gcc and has not received a package upgrade (besides security/fixes) since 8 years. So nobody should be surprised that it does not fully support recent software. Security upgrades does not matter in that use case because security updates are usual no major or minor package bumps. Also nobody uses Ubuntu ESM for 500$/yr for tvheadend, seriously.

So what are the realistic options ?
- freeze dependencies that they support EOL distros (ofc likely they break with more recent distros)
- find workarounds/patches that new stuff still builds at old distros with old toolchains
- backport more recent toolchains to EOL distros
- just build a basic Tvheadend without ffmpeg for EOL
- release Tvh 4.4 and create a Tvh LTS build, drop old distros at master

Its just a matter of how much effort you are willing to spend to keep the old stuff alive.
Pretending that 10-year-old distributions should still support cutting-edge software doesn't solve the problem.

**Comment by mralapete** [comment]
> Who said, that anything will be deprecated? And as far as I am concerned I think it is (still) my decision which OS's are in the CI and what changes are merged and what changes aren't. There are just more people who could take over in case I get hit by a bus or whatever, and those people are also taking care of other non-code-related tasks like migrating the issue tracker to GitHub, operating/migrating/archiving the forum and taking care of the domain registration, signing up for providers that offer free services for open-source projects and their maintainers, maintaining a publicly accessible list of services we are using for transparency and so on. Or in different words: Various things that should be done but that I don't really have time for. To be clear: I don't think that anything is geting taken out of my hand that I don't want to give away. There is a lot of communication in the discord channel (which you are more than welcome to to join aswell) about what is done and what isn't, just because I am not the one communicating "something" doesn't mean I am not involved in the decision in some way.
> 
> I "like" the idea of re-purposing old hardware and I know from personal experience that it often comes with outdated operating systems. So I am trying to provide packages for old distributions as long as somehow possible with reasonable effort.

I get you completely. Unlike some around the open source world I don’t have endless resources to throw at the latest “tech toy” available in the market place. I repair rather than replace and this repaired equipment in many cases relies on older iterations of current OSes. I certainly won’t be consigning my current hardware to the recyclers on account of any unilateral decision to deem it unusable.

I do understand that you have been a focal point of the TVH project for some time since many of the originators slowly slipped away without any notice and without a succession plan. Not a particularly envious position to find yourself in. 

This might be an opportune moment to indicate to the user base the people who have been assigned these other tasks you’ve mentioned, as was done in the past. No need for any personal details or what they had for breakfast or what personal adventures they are embarking on. Just the basics, like a who’s who so the users know who and what they are dealing with.

I assume work is still underway refactoring the TVH forum as it clearly needs it. Maybe some form of announcement on a timeline might be pertinent here.

I for one am truly grateful for your continuing efforts to date. Hopefully we can soon get to a stage where some of the load can be taken off your shoulders by serious volunteers who understand what’s involved in a project and not some journeymen trying to add some extra kudos to their CV.

**Comment by Flole998** [comment]
> This might be an opportune moment to indicate to the user base the people who have been assigned these other tasks you’ve mentioned, as was done in the past. No need for any personal details or what they had for breakfast or what personal adventures they are embarking on. Just the basics, like a who’s who so the users know who and what they are dealing with.

The idea was to do this on the new forum. There is no point in making an annoucement/making a list and then "deleting" it because the forum where the announcement was made is gone.

> I assume work is still underway refactoring the TVH forum as it clearly needs it. Maybe some form of announcement on a timeline might be pertinent here.

I am not really sure about the status to be honest.

**Comment by uknunknown** [comment]
Is not an Ubuntu 20.04 problem ... I test it on Lubuntu 20.04 x64 and works ok. 
Can someone clarify what platform/OS is: "buster aarch64"? I assume is some raspbian ... but what version and running on what raspberry pi version.
stretch and ubuntu 16.04 have a different error than other failures - so those might be a lost cause.
I see 3 options:
1. do nothing --> we wait at 1.13.1 until we decide to drop some platforms or hope that VPX will be fixed for aarch64.
2. drop stretch and 16.04 --> try to recover the other 3; maybe VPX will be fixed on newer platforms.
3. drop all 5 ... I am tempted to say we should not do that. There are some speed improvements highlighted in change log but is questionable the improvement versus loss of platforms.

**Comment by Flole998** [comment]
The CI says it failed on 20.04 though. I won't just drop some platforms because something doesn't compile on them anymore, especially some recent-ish platforms. buster is Debian buster.

**Comment by uknunknown** [comment]
I was able to repro the problem using: RPI4  with ubuntu 20.04 64 bits (flashed using Raspberry Pi Imager).
I found the commit that is generating the failure: 91158c99f   (SHA: 91158c99f7bc241bf70bca597f289c681c71956b)
I was able to compile 148d1085f   (SHA: 148d1085f79c6b4dd07d552cb51b53bd2e87a3aa)
The bad news is that https://github.com/webmproject/libvpx is a mirror of https://chromium.googlesource.com/webm/libvpx so fixing this problem ... probably has to be manged though google git.

**Comment by uknunknown** [comment]
I reported the issue on https://groups.google.com/a/webmproject.org/g/webm-discuss .... but for now my post is not shown (I don't know if needs to be validated or I didn't post it right).

**Pull request merged**
